### ISSUE TITLE
Any possibility to use output of repeatmodeler for LAI evaluation?

### ISSUE THREAD

**Issue by MeiyuanJi** [oushujun/LTR_retriever#103]
Hi, 

I am working on a maize genome. After assembly and scaffolding, I used repeatmodeler to generate a repeat library with argument "---LTRStruct". The output contains LTR sequence annotation. For LTR_retriever, is there any possibility to feed it with output from repeatmodeler or repeatmasker for the LAI calculation? Otherwise, I need to rerun LTRharvest by myself although repeatmodeler already employed LTR_retriever for its task.

Many thanks in advance. 

Best,
Meiyuan

**Comment by oushujun** [comment]
No, you need to run LTRharvest and LTR_FINDER for LAI.  Using only
LTRharvest results will have lower LAI.

Shujun
