### ISSUE TITLE
xxx.genome.defalse is empty and the soft seems aborted

### ISSUE THREAD

**Issue by zouxq97** [oushujun/LTR_retriever#106]
Hi, shujun
Thanks for your nice peration and maintenance for LTR_retriever software.I have performed the software and very smoothly in other species until now.But when I operated in a new species and I suffered a problem in prossess.When the log file showed that 'Modules 2-5: Start to analyze the structure of candidates...'，I found the output file xxx.genome.defalse in this step were empty.And then I checked the procedure that I ran,there were many '[perl] <defunct>' procedure.But time went away,the procedure still didn't continue and the output file was still empty. I don't know what has happened and how to deal with.

I will appreciate it If you could supply any suggestions.

**Comment by oushujun** [comment]
Hi, what version of LTR_retriever you are using? - Shujun

**Comment by zouxq97** [comment]
Hi，the software version I am using is ltr_retriever-2.9.0-0
| |
邹小晴
海洋生物学
|
|
厦门大学海洋与地球学院
18237325007
***@***.***
厦门大学翔安校区周隆泉楼B2-311
|
---- Replied Message ----
| From | Shujun ***@***.***> |
| Date | 08/20/2021 00:44 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [oushujun/LTR_retriever] xxx.genome.defalse is empty and the soft seems aborted (#106) |

Hi, what version of LTR_retriever you are using? - Shujun

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zouxq97** [comment]
> Hi, what version of LTR_retriever you are using? - Shujun

The software version I am using is ltr_retriever-2.9.0-0

**Comment by zouxq97** [comment]
Info update for you!I adjusted the number of threads to the minimum, and then found that the program is running normally, it may be that there is a problem with multi-threaded parallelism, thank you for your attention and feedback.

**Comment by oushujun** [comment]
Thanks for your feedback. Maybe your perl is not set up to use multiple processors. You may create a new conda environment and install a new perl and new LTR_retriever in the environment. - Shujun
