### ISSUE TITLE
Issue with bin/make_lib.pl 

### ISSUE THREAD

**Issue by RanZhou** [oushujun/LTR_retriever#107]
Hi,

I got this error/warnings during module 2-5:
"use" not allowed in expression at /apps/eb/LTR_retriever/2.9.0-foss-2019b/bin/make_lib.pl line 9, at end of line
syntax error at /apps/eb/LTR_retriever/2.9.0-foss-2019b/bin/make_lib.pl line 9, near "use warnings
use strict"
Execution of /apps/eb/LTR_retriever/2.9.0-foss-2019b/bin/make_lib.pl aborted due to compilation errors.
mv: cannot stat $genome.fasta.ltrTE.pass.tmp.clust: No such file or directory

Do I need to worry about this?

Thanks,

Ran

**Comment by oushujun** [comment]
Hi Ran,

Thank you for reporting. I have fixed this. Please update your software and try again.

Best,
Shujun

**Comment by RanZhou** [comment]
Hey Shujun,

After that was fixed, I  ran into some new issues:
Use of uninitialized value in numeric gt (>) at /apps/eb/LTR_retriever/2.9.0-foss-2019b/bin/make_lib.pl line 48, <Clust> line 1.
Argument "motif:TGCA" isn't numeric in numeric gt (>) at /apps/eb/LTR_retriever/2.9.0-foss-2019b/bin/make_lib.pl line 48, <Clust> line 1.

And in Module 6: Start to analyze truncated LTR-RTs...

ERROR: No such file or directory at /apps/eb/LTR_retriever/2.9.0-foss-2019b/bin/make_lib.pl line 11.
mv: cannot stat â€˜$gGenome.fasta.ltrTE.tmp.clustâ€™: No such file or directory

Although the jos seems to be finished, but I'm not sure if these issues will impact the results.

Thanks,

Ran

**Comment by oushujun** [comment]
Hi Ran,

Something is wrong. You may need to test the installation with a small
genome.

Best,
Shujun
