### ISSUE TITLE
LAI seems not working...

### ISSUE THREAD

**Issue by xhzy940301** [oushujun/LTR_retriever#116]
Hi
The software has already generated the files shown in the screenshot, however, the Harvest file has not changed for a week. I don't know whether there is a problem, the system still shows running.

Your best
Zuoying
[
![image](https://user-images.githubusercontent.com/57342415/157178326-3877ec0a-4982-4d87-9d77-e4d2037bdd66.png)
](url)

**Comment by oushujun** [comment]
Hello Zuoying,

This is not yet the LAI step. If your LTRharvest is stuck, you may re-run it. You may also consider this multi-threading version: https://github.com/oushujun/LTR_HARVEST_parallel

Best,
Shujun

**Comment by xhzy940301** [comment]
Hi Dr. Ou

Thank you for your answer. I will try to re-run it.

Best,
Zuoying

**Comment by xhzy940301** [comment]
Hi Dr. Ou

I've tried to use the parallel version, the error file has many errors like below:
![image](https://user-images.githubusercontent.com/57342415/165013834-283e3ca9-5f79-4b05-af5a-880e2c29c1a0.png)
and the scn file showed this:
![image](https://user-images.githubusercontent.com/57342415/165013908-d5ff49b3-f163-4464-84ff-7547c49c896c.png)
I don't know why...

Best,
Zuoying

**Comment by oushujun** [comment]
Please use default parameters.

Shujun

**Comment by xhzy940301** [comment]
Dear Dr. Ou
    I finally found the point. Because the contigs ID (Canu results) has too much information, the parallel version works fine after simplify the ID.

Best wishes
Zuoying

**Comment by oushujun** [comment]
@xhzy940301 Glad that you found the issue. It's always recommended (or required) to simplify your sequence IDs before any analysis. Good luck with your project! - Shujun
