### ISSUE TITLE
Stoped in the annotation step

### ISSUE THREAD

**Issue by wensulin93** [oushujun/LTR_retriever#119]
Sat Apr  9 02:30:50 CST 2022	Total intact LTR-RTs found: 5470
				Total intact non-TGCA LTR-RTs found: 21

Sat Apr  9 02:30:55 CST 2022	Start to annotate whole-genome LTR-RTs...
				Use -noanno if you don't want whole-genome LTR-RT annotation.

**Comment by oushujun** [comment]
Hello @wensulin93, can you provide more information? I could not tell anything wrong with the above. - Shujun

**Comment by wensulin93** [comment]
Okay, that's done. The speed of the previous system was too slow, and the results were achieved quickly by changing the speed of the server.
