### ISSUE TITLE
RepeatMasker is not running properly

### ISSUE THREAD

**Issue by qingyun-mei** [oushujun/LTR_retriever#121]
Hello Shujun Ou：
when I run the LTR_retriever, It happened errors as follows: 
ERROR: RepeatMasker is not running properly!
	Please check the file Genome.fa.ltrTE.mask.lib and Genome.fa.ltrTE.trunc and test run:
		RepeatMasker -e ncbi -q -pa 20 -no_is -norna -nolow -div 40 -lib Genome.fa.ltrTE.mask.lib -cutoff 225 Genome.fa.ltrTE.trunc
In addition, I checked the files and found  Genome.fa.ltrTE.trunc file was empty.  Could you  give some suggestion? Thanks

**Comment by qingyun-mei** [comment]
Thanks for your help. The result is as follows:
grep trunc Genome.fa.defalse|wc -l
7322

**Comment by oushujun** [comment]
That looks good to me. Can you try to rerun it or list the size of files in
the work folder?

**Comment by qingyun-mei** [comment]
Hello shujun:
I have rerun it many times and the result is always same. The size of output file is as follows. Thanks very much!




Best regards!










At 2022-04-13 11:50:55, "Shujun Ou" ***@***.***> wrote:

That looks good to me. Can you try to rerun it or list the size of files in
the work folder?

**Comment by oushujun** [comment]
Hello @qingyun-mei,

I didn't see the size of files. Can you share it again? Thanks.

Shujun

**Comment by qingyun-mei** [comment]
Sorry, maybe there are some errors in picture. The size is as follows:
2.0G	Genome.fa
4.6M	Genome.fa.finder.combine.scn
5.0M	Genome.fa.retriever.scn
5.0M	Genome.fa.retriever.scn.list
2.5M	Genome.fa.retriever.scn.full
512M	Genome.fa.ltrTE.fa
486M	Genome.fa.ltrTE.stg1
145K	Genome.fa.ltrTE.fa.cleanup
2.4M	Genome.fa.retriever.scn.extend
491M	Genome.fa.retriever.scn.extend.fa
994M	Genome.fa.retriever.scn.extend.fa.aa
33M	Genome.fa.retriever.scn.extend.fa.aa.tbl
87M	Genome.fa.retriever.scn.extend.fa.aa.scn
4.9M	Genome.fa.retriever.scn.extend.fa.aa.anno
17M	Genome.fa.defalse
9.4M	Genome.fa.retriever.scn.adj
0	Genome.fa.ltrTE.stg3.otherTE.out
47	Genome.fa.ltrTE.stg3.cln.exclude.list
0	Genome.fa.ltrTE.stg3.cln.clean.exclude.father
0	Genome.fa.ltrTE.stg3.cln.clean.exclude.child
0	Genome.fa.ltrTE.stg3.cln.clean.exclude
0	Genome.fa.ltrTE
0	Genome.fa.LTRlib.exclude.tgt
2.9M	Genome.fa.pass.list
79K	Genome.fa.nmtf.pass.list
79K	Genome.fa.ltrTE.pass.nmtf.list
2.9M	Genome.fa.ltrTE.pass.list
3.0M	Genome.fa.LTRID.list
196M	Genome.fa.ltrTE.pass
196M	Genome.fa.LTRlib.raw
324K	Genome.fa.ltrTE.trunc.list
0	Genome.fa.ltrTE.stg2
3.7M	Genome.fa.ltrTE.pass.clust.clstr
700K	Genome.fa.retriever.scn.adj.list
0	Genome.fa.ltrTE.trunc
33K	Genome.fa.ltrTE.veryfalse.list
10K	Genome.fa.ltrTE.veryfalse
2.0M	Genome.fa.ltrTE.veryfalse.fa
2.0M	Genome.fa.ltrTE.mask.lib

Thanks!


> Hello @qingyun-mei,
> 
> I didn't see the size of files. Can you share it again? Thanks.
> 
> Shujun

**Comment by oushujun** [comment]
Hello, 

What version of LTR_retriever are you using?
Can you try this:
`cd-hit-est -i Genome.fa.ltrTE.pass -o Genome.fa.ltrTE.pass.clust -c 0.8 -G 0.8 -s 0.9 -aL 0.9 -aS 0.9 -M 0 -T $threads`

Thanks,
Shujun

**Comment by qingyun-mei** [comment]
Hello shujun:
Thanks for your reply. I run 2.8.7 and 2.9.0 version. The result was same whenever it was installed by conda or standard installation.  when I try: cd-hit-est -i Genome.fa.ltrTE.pass -o Genome.fa.ltrTE.pass.clust -c 0.8 -G 0.8 -s 0.9 -aL 0.9 -aS 0.9 -M 0 -T $threads, it seems normal as follows. Maybe this process will take a long time. I terminate it after a few minutes


Program: CD-HIT, V4.8.1 (+OpenMP), Apr 07 2021, 10:57:21
Command: cd-hit-est -i Genome.fa.ltrTE.pass -o
         Genome.fa.ltrTE.pass.clust -c 0.8 -G 0.8 -s 0.9 -aL 0.9
         -aS 0.9 -M 0 -T 10

Started: Sun Apr 17 12:15:04 2022
================================================================
                            Output                              
----------------------------------------------------------------
total seq: 62390
longest and shortest : 14548 and 95
Total letters: 193138231
Sequences have been sorted

Approximated minimal memory consumption:
Sequence        : 201M
Buffer          : 10 X 15M = 158M
Table           : 2 X 17M = 35M
Miscellaneous   : 5M
Total           : 400M

Table limit with the given memory limit:
Max number of representatives: 832455
Max number of word counting entries: 18446744073463416722

# comparing sequences from          0  to       5199

**Comment by oushujun** [comment]
You may want to test LTR_retriever with a small, simple fasta file to make sure it's running properlly.

**Comment by wrengs** [comment]
Dear Oushujun & Qingyun-mei,

Sorry to comment on this existing issue, but I am experiencing the same error.

I previously successfully ran LTR_retriever on a 833 Mb genome. 
- LTR_retriever v2.9.0
- RepeatMasker version open-4.0.6

Next, I repeated the workflow on a different genome, 871.9 Mb in size (sequence names <12 characters)
 
grep trunc Moneyberg_Hifiasm+Canu.fasta.defalse | wc -l
1883

I got the following output & error:


Tue Apr 26 13:08:26 CEST 2022	Dependency checking: All passed!
Tue Apr 26 13:08:41 CEST 2022	LTR_retriever is starting from the Init step.
Tue Apr 26 13:08:44 CEST 2022	Start to convert inputs...
				Total candidates: 19727
				Total uniq candidates: 18673

Tue Apr 26 13:08:50 CEST 2022	Module 1: Start to clean up candidates...
				Sequences with 10 missing bp or 0.8 missing data rate will be discarded.
				Sequences containing tandem repeats will be discarded.

Tue Apr 26 13:23:29 CEST 2022	17574 clean candidates remained

Tue Apr 26 13:23:29 CEST 2022	Modules 2-5: Start to analyze the structure of candidates...
				The terminal motif, TSD, boundary, orientation, age, and superfamily will be identified in this step.

Tue Apr 26 14:14:45 CEST 2022	Intact LTR-RT found: 4722

Tue Apr 26 14:18:59 CEST 2022	Module 6: Start to analyze truncated LTR-RTs...
				Truncated LTR-RTs without the intact version will be retained in the LTR-RT library.
				Use -notrunc if you don't want to keep them.

Tue Apr 26 14:18:59 CEST 2022	1782 truncated LTR-RTs found
**ERROR: RepeatMasker is not running properly!**
	Please check the file Moneyberg_Hifiasm+Canu.fasta.ltrTE.mask.lib and Moneyberg_Hifiasm+Canu.fasta.ltrTE.trunc and test run:
		RepeatMasker -e ncbi -q -pa 20 -no_is -norna -nolow -div 40 -lib Moneyberg_Hifiasm+Canu.fasta.ltrTE.mask.lib -cutoff 225 Moneyberg_Hifiasm+Canu.fasta.ltrTE.trunc
	Please report errors to https://github.com/oushujun/LTR_retriever/issues
Program halt!

I test ran RepeatMasker with the suggested settings ( Search Engine: NCBI/RMBLAST [ 2.11.0+ ] ) and it successfully finished in 170 batches (attached).
[20220502_repeatmasker_nohup.txt](https://github.com/oushujun/LTR_retriever/files/8603165/20220502_repeatmasker_nohup.txt)



Next, I tried re-running LTR_retriever, unfortunately without success as the same error occurred.


Do you have any suggestions where to start looking for a possible solution?

Many thanks in advance!


Kind regards,
Willem

**Comment by oushujun** [comment]
Hi Willem,

Can you test your LTR_retriever version with this toy genome: https://github.com/oushujun/EDTA/blob/master/test/genome.fa

Shujun

**Comment by wrengs** [comment]
Hi Shujun,

Many thanks for the quick reply.
I ran the LTR_retriever workflow (as suggested on https://github.com/oushujun/LTR_retriever#usage )

LTR_retriever ran through the 8 modules and finished without any errors.
Downstream LAI (beta 3.2) also finished analysis, although no LAI was produced due to too low LTR sequence content.

Please find attached the nohup output file. 
[LTR_retriever_nohup.txt](https://github.com/oushujun/LTR_retriever/files/8609466/LTR_retriever_nohup.txt)

Does this match what is expected for the toy genome?

Kind regards,
Willem

**Comment by oushujun** [comment]
Hi Willem,

Yes if it finished without error on the toy genome, it should be working
properly. You may want to check your genome for any potential issues.

Shujun
