### ISSUE TITLE
Too many 0 LAI values

### ISSUE THREAD

**Issue by wensulin93** [oushujun/LTR_retriever#122]
Hello, @oushujun 

Most LAI values of individual species generated by using the LTR-retriever run are clustered at 0. What is the problem? Is it a very small number of transposons, or is it a sequencing problem, or what?

Here are the software parameters:
```
LTRharvest
gt suffixerator \
  -db 1.fa \
  -indexname 1 \
  -tis -suf -lcp -des -ssp -sds -dna
gt ltrharvest \
  -index 1 \
  -similar 90 -vic 10 -seed 20 -seqids yes \
  -minlenltr 100 -maxlenltr 7000 -mintsd 4 -maxtsd 6 \
  -motif TGCA -motifmis 1  > 1.scn &
 LTR_FINDER
ltr_finder -D 15000 -d 1000 -L 7000 -l 100 -p 20 -C -M 0.9 1.fa > 1.scn &

LTR_retriever -genome 1.fa -inharvest 1.harvest.scn -infinder 1.finder.scn
```

The species are Rhododendron williamsianum and Rhododendron simsii. The assembly link is:
1. https://www.ncbi.nlm.nih.gov/assembly/GCA_009746105.1/
2. https://www.ncbi.nlm.nih.gov/assembly/GCA_014282245.1/

LAI distribution pictures are as follows:
https://weibo.com/2215415680/Lp043sOxg

So that's Question 1

Question 2 is whether the following LAI distributions are also normal? It seems that there are too many 0 values:
https://weibo.com/2215415680/Lp21UyZUV

I was led here to ask questions.

That should be the last question. ^s^
Thank you so much!

**Comment by oushujun** [comment]
Hello @wensulin93,

If you can run LAI without errors, that means the program is performing as expected. If you get 0 LAI value for your genome, it suggest the repeat assembly of this genome is not good. The interpretation also applies to reigonal LAI values.

Best,
Shujun
