### ISSUE TITLE
What is the difference between LTR Unknown and NA Unknown?

### ISSUE THREAD

**Issue by jia-wu-feng** [oushujun/LTR_retriever#123]
Dear Shujun,

I use the new version LTR_retriever, and a lot of results are NA Unknown. I am curious what is the difference between LTR Unknown and NA Unknown in the results?

Thanks,
Jia-Wu

**Comment by oushujun** [comment]
Hello Jia-Wu,

Sorry I just saw your message. Can you give some examples of these sequence IDs?

Shujun

**Comment by jia-wu-feng** [comment]
<img width="2013" alt="image" src="https://user-images.githubusercontent.com/24247803/167710301-bd3a456a-688c-4423-8e0c-4f3016057b69.png">
>chr1H_3:293323..296892_LTR#LTR/unknown
TGTAGCGACCCGACTCAAAACGAGTCAAGCCTCTGTGTATCTGTGCCATCCCTGGATCAGTATGCTGGCACACACAGTACATCAATGTATTTATCAAAGTGCAATCACATGTAAATAGCGTAAAACTGATATATACCTTAAATATCGCAGCGGAAACAGTCAAGGGAGTGGAGTCCCAATAAACACCAACGGCAAGTTGAGTGCGGACCGTAACCCTGAATCGTACTCTTACTCGTCGAGAAAAATATCTGCAACATAAGACGTTGCAGCCGTGTAGGTCAGCATATTGAATATGCTGGCAAGTCACCAAAGAGAGGGGTGAAAATGTAATCATCTATACTATATGCATATATGGCAGGAGGGGTTGTAAGTTTTTAGCGTAAAGCAAATTTTCTCCTACAACAAGAGGGGCTAAAAGCAAAACATTACTACAAGGTTGGTTGTTAACGAGATGGTTCCGCCAACCAATTCTCGTACCCGAGTTGTCAGTAACACCCACATCAATATTATTATAATGGTGTTGAGAATTTCAGATAACTTCAGTTCCTTTGGCTCAAGTTGTCCATGACCGTGGACACGGCTAATCGATTAGGTTTGAGTACTCTGCAGAGTTTTGCACACGTTCCCCACAAGATTTGATCGCCTCCGTGTATGTCCTCGCACTTCAGGGTGTTTGAAGACCGGAAGATCAAAACATGGTCTTTCAACGGGTCCCTCTGAATCCCTGTCGGTGCCCATCCAAATCCTACCGTTCTTCTACATCTGCTAGCACCGCCTGTCCAGAGTCGCCACGTTGTCCAACCAAGCCAGAGCCCATAATGGCTTGTGGCTGTGCAGGTAAGCCTTGGGTCTTGAAAATATCCGTCCGTCTCTTTGAGCCTGGGTGAAGCTTTCCGCAAGATGTCATGGCACGTCTCCAGCATCCCGGGCATCCACTGGTTTCTCCAGGGAGCCGATCAACCGTCCTTCACCCAGAGTTGCATTGCATCACAAGGTCTTGAAAAGTCTTGACTTAACCGGTCTTGGTTATTAAATTATTCTCGCATCACTCGTGATAAACTCTCAACCAGAATCCCGTCTACTCACGCATAGCAATATGAAATTTGTCGTCCCGGGCCAAGTGACGGGGTTGTTGGATGCCTACCACATGATACTACAATATGTAACCATAATTTCCAAGTACCTACTCAGCATGCAATTGGGCAAAGAAAGGTGGAACTACCATGCATAGAAAACATAGGTGATAGTATGATCAAAGTGACTTGCCTGGTGATGTTGACGAAGAAGAATTATCGTTCTCGAGAAAATAACTTGATAGACTACTCGTCACTCTCCGATGAAATCTATATAACAAACATATCATTCACATAAGCACTCACACTAACAATCAAAACAAAAGAGAGAGCGAATAAGAATCCGAAGAACTTCAAATAAAACTAGTGAGTCTTCTTCTACATCAAACACTAAATAGTTTTTGTTCTAACTGAAAGTAAAACATTAAAATAACAGAGAACTAAGATATAAATTTAACTAAGATAAAATAAAGTATTTTTCATAAAACTAATTGAAAGTATTTTCAAATGGGAGTTGAAACCGTAGAGAAATCAATTGCAAGTTATTAGCAAACTTGAATTGATTTCACGATAAAAAATAAAATTAAAATAAAAACTTGTTGAACACCTACTGTTTAACTAACAGAAACTAAACATAAACTTTCTGAAATATAAAAGAAATTAATTTAAAAACAACTAAAGAAAGAGACTTTAGTCACAATCCTAAAAGAGGTGAAACAGAAATTGTTTCACATGAAATAATGAGTTAAAATGCTCAAACAATTCTGAAATTTTTACCACTGATAAACAAGATCACTAGTGATCAGTAGCAAAAGAATTAATTTAAAATCTATTTTTAAACTCCCGGAATAAGCAAAACAAGCTTTAAATCAAATCTGATCTAACTAAATTTTTATAAATCCAAATATAGACAAATTATATATTTTCGGAAACTACAAGAAAATTGTGATCTAACGCAAAACGAATCAGCATCATTGGACTTCTAGATCAAAAGTTATGGCCAAAACAAAATTGGAACTTTCTGTTTTTTGCAATTTAGACAGAAAAACTGAAGTTGACTAGCTAACAAATAGGGGTACACGTGGCGCACTACTATAGGCTGCGGGGGGTGTTTGTTGCAACGTTTGGAGCAAACGGCCGAGGCTAACAAAATTTTTCGGTTAAAACATAAGTGAATTAAAACCGCCGGTTTTCTACTCTAAACCGAAGGGGTATACTAGGGATCTAATCTACACCATCTAAATATGATCTAAGGGCTACTAAAGAAAAACAAAAAGAAACAGGAGGAGGGGATGGAGCCTTACCGTGGTTGGAGATGCTCCCGTGGCTGCTGGTGGCGAGGTGGAGGGGGGGGCTCCGGTGGGGTGGGGAGGGGCCGGCGGGAGGAGGGGGAGTGGCAGGGGGCGGTGGGGCTCCTGGGGGGGGGAAGGGAGGCGAGGTGGAGGGGGTCTGCAGGGGGGGGCGAGGGGGGGGGGGGAACTGCTGGTGTGCTGCTGCTCGTGGCAATGGCGATGGGGAGATGGAGAAAGGGCAGCAGGGGGCGGTGGAGGGGGTGCAGGAGGGTGCGGCAGGGGTGCCAGGGGGCGAGGTGGGGCTGGGGCGAGGTGGATTCAGCTCCTGCCGAGCTCCTGTCAACAGAGAAGATGGCGACGGTGGCGCCGAGGCTACGGGCGGGGAAACGGAGATTTTTTTAGGGGAATGGAACGAGGAGAGGCGGGGCATTCTTATAGAGGCGACGGGAGGCGCCGGGAGGAAGTATAGCTCGCGAATCCCGGAGGGGAAGCTTCTTGGGAAGCTTCTGCCATGGTACAGAAGGCAACGCTTGAGGTAGAAGAAGAAGGTGCGTTATGGGCCTGGTCTGTTTCCTAAGGTGGCCCAGGTACATTCCTAAAATAAGAGAGCTCTTTCCTTTTTTATTAAATCAGGGGTTAATACTATTAAAAGCAAATGGAATATTCCTCGGAATATAGGGGTATAATATATTAAAATTTTCAGAAAAATAAATCCAAAAAGATGGGCATTTTTCCACTACCAAAATAAAAACTTCAGAAAAAATTATTTTCACAAAATGGCCTAAAAGATTTATTTTCTTTTGCAAATAATTTTCAAATGACCCTCTAGGTTTTAGGGTTCAAATAACTTTCAAAATGTCCATGGGTTTGAGGGTCATGTTCCTCCTCTCTTTTTTCTGTTTGACAGAAAGTATTTCCCGGCATTTCTTGCACGAAGAAAACAAGTAAAAATGCAAGAGAATTCAAATGCAAATATCTCCGTTCAAATTCTTTATAGTTGAAGAAGTCATGTCATCTTCTCTCGTTGCTTTTAAAAGATTGAATTTGAACTCATCGGAGAAGGGGAAAGTCATTTTATTCCCTCTCATTCAAAAGTTTCGAAAAGTTTCAAATTCCACTCAAGTTTCAATCACTCATTCAAACAAACAAACAATTCTAATAATTATTTTTTTTTTTTTTAACATTCCAAAATTTGGGATGTTACA
>chr1H_3:296893..300367_INT#LTR/unknown
AACCTACCACACTTAAAAATGAATCTCGTCCTCGAGATTCGAAGAGGCTAGAAAGAAAGGTTAGGGTTTGGGGTCTTCTAACAAATCCGATCTCTTGCAAAAGTGGGATGCTACCACACTTAAAATGAAGGTTACTGGTCCCTTAAAATTTTAACAATCCTCTGGGGTTTTGGCATCTGACTCCTCACAGTCTTCATACTAACTCCTCTGGTGATGCTCTTCCGTTATACTCATAACGTTCCCATCAAAATCGAGGGTTCTTCTGTTGATATAAGCTACTTCCGTTTACTGGGTCTTCTTAACTGACAGTCTCGTGGTCAATTCTAAATAACCTATCGATGATTCTCATGGTGGTCTACCATTTGTGGTTATCCTGCAGAGGGAGAGGTCTTGTCTTCATCCTCACCGTAAAATTTCCTACGCGTGACAACAAGTGCCATGTACATGGGCTTTTCCTATACCATTCTAAGGCTTAAACAAAAGCTTCAAAGAACGTCGACTCTCACTATGGGTAAGTCTCTCAGATTTACCATTCCGAATAGCAAGAGAATGATAATAGTAAGTCGTCATGGTGGCCAAGCCATGTCGCACTGAAATCATTACCTTGTATAAGGCTTAGGGAATCTCGTATTCTAACACTTGGGCATCCTCACAAGCATTGCGGAATTTCTCTTGTCCACGAACGAAGTTCGGATAATCCATTGGTTCTGCAAGCTGAACAAAACATCTATCGTAACTTCACAACTCTCAGGTTTTCGTATGCTCCTAAGAAAACGTTTTGCTGATCCGTCATAACTTCTTCCAAGTTTCTTTCATCATCAAGGTAGTGTTGGATCCTTATTAGTCCTTGGGTCTGTGGGTTGCAGGCATACTTGGAATTACTCCGCCTTTAAATTCCATAGTATTTCATTCCATCATATTCTTGGGGTAACCATCATATAATAATAATTCCTCAGACTTATTTTTGGTTCACACACCACTCTGTGGGATGCTTTCCATTGGTGTGTTTACCATGAAAAGGTATTGGTTCATCCATAAATCATATTCATTTCATAATCAATCCTTTATTACATCCTTCATTTCTTCTCAAAAACTCTAATTCAAAAGTACTTTATTACAAATGCTGCCATCCACATTGTTCGGTATGGTCGAGCATTTTTGCCAACTTTATTCATTAGTCTCCCTTGGAGATACTTTAGTTCCACTGGAACTTTCCAATGTGCTCCTTGAAATCATCCATCTTTTGCTTCATCATGGTGGCCATAAGCTTCATCTCCATCATCTCTGCACGTACCTCACTCAGGTATTCCAGGGTATGACGGAGTCTTGCTTCCAGTATTTCTCCAATCTGACGTATGGCTTCCATGGCAGCTTCACGAACAGCATCAAAGAAGGTTGCTCGTGGTACACGTGAAATGAAAAAGTATTGCCCCATAGTCTTTGGACAAACTCCTTTCACATGGTGGAGGTGTACTTCCACATACCAAAGTTCCGCTCCATTTTCCATGAACGGGTAGCCTTTGTAGACTGCATCTCCTTCAAGATGAATGTGCTTCATCGTGTCCTTCAGGATTTTTGGGTAATCATGATCACTGGTCAGGGTCATGATCGTTTCTGGGCCCTTGAGGAATGACTCGTAGAGAGTTGTCATCTGCAGGTGTCAGAAAATAGGTACTCAGAGGAATGTATGTGTCTCCTTGGTAATTATGGTACATTCCTACTCAGTGGATCCTGTGGGTTTACCGATTACTACCACACTTAAAATGAATTATACTTATGCCTGCATAGACCATATTTTCTCATATCCTCATAATTGTTCAGAGACCTTTGTTCGGAGAGAACAACGCATACAGTTTCAACATAGGCAATCATGAGACAATAAATTCCATTTATTCATGATGTTATTACAATCTCAGGGACTTCTGTTACAAAAATTTCACTCCATGATCTCATGAAAAACAAGAGTTCTTCAGATTACAGTAATTGCCGCGGTCAAAACTTAACTACTCCTTTTAGCTTTCTTCCTTTGTGGACAATCATTAGCAAAATGTCCTGCTTCCTTGCAACGAAAGCAAATGAGTTCTGACAAGTCTCGAGGCATCTTAGTGTTTGCTTTTGCTCCTTGGGTTTCCGGCTTCCTTCCTGAGCACATGTATTTGTGGTGGCCAAATTCCATACACTTGTAACATCTGTCATGACTCAGGTCTTTATCTACAGAGAGTTGGCTCTTTCGAGGGTTCTTTTTCTTCTTTCCGGACTCCTTTGTTTTGGCCAGTTCTTCTATTTCAAGTGGATCAAACTCCACTTTTTCTGCCGGGAAGTTTCCCAGATACTCTTGGCTTCCCTTCGTGCAATCCTGTGAATAATGTCCTTCTTCTCCACATGAGTAGCATGCATTGGAGAAAAATCTGGTCAGACCTTGTCCATCAGGGTCTTCTATATTTTCATTCTTCACAGGTTCTTCTGGAGTCTTCTTCTTGAGGGTTTCCTTCAGTGCATCTTTCTGCTGCTTGACAACTTGTTGCACCTTGGGGTAAATGTGACACTGAGCTGGATAGTGGTTGGTTCCTTCACAAAGGAAACAAGTCACCTGACTACTTGGGCACTCCTCAGCTGGGTGATTTTCTTCACAATGAGTGCATCCACCCTTGTGTTCTTCCTGGGTGTGTCCTATTTCTCCACAGATCTTGCATGCACAAGGCTTCTTCATCGGATTATCATAGCACTTCCGAATGAGACGGGATCTTAACAGAGTCTTCTTGAATTTGTCCCAGGTTTCTGCTCCACTAAATCCTTGTATGGCATGGTGCATTTTCCACCAGATAGCAGCACTTTGGGTAAAGTACTGGAGAGCGTGCTCCATTTCATACTTCCTTGAGATCAAGTTGCTCCCGAAGTGGTTTTCCATGTTCTGAATCCATATTTCAGCTTCCAGCTGGGTCATTGGTCCAGAGACTACAAGTCCAGCTTCATACTCCATCTGGTAGGGTTGAGGTTTTGGGGATGAGACGGGTAAGAGAGAGAGGGAGATACACACAATACAAACAACATTTTTGAGAATAGGTTTTATTTGTGGCCGTCGGAAAACACACGCCAATGACGGCTCACAAATCATCGTAACTAACGTGGGTATATAACAGGGATTTGGACTTCTAATGGTCATATAAATATTCGAACGCTTCAGGGTCTTTGAATTCTTCAGGTCTTGAGAGTCTTCAATGGGTGTAGCTTCAACTCTTCAAATGCATGGTGAAATCCTCTTTACTTTGAAGTAGAACTCCATTGATTCTTCATGTGGTCAAAGAGAAAGGCATTGTCTAACTATTTGAGGTGAGAGAGAAACATTTGATGAAATCAGGAGAGATGAGGAGTAAAAGGTGTTCTTTAAAATAAAAAATTTGAGAGATCCTTTCCTAAGAAATTTCCAGTTTCTAGGGTCACGTCCTACAGTCAACATGTGCTCTGATACCATCTC
>chr1H_3:300368..303934_LTR#LTR/unknown
TGTAGCGACCCGACTCAAAACGAGTCAAGCCTCTGTGTATCTGTGCCATCCCTGGATCAGTATGCTGGCACACACAGTACATCAATGTATTTATCAAAGTGCAATCACATGTAAATAGCGTAAAACTGATATATACCTTAAATATCGCAGCGGAAACAGTCAAGGGAGTGGAGTCCCAATAAACACCAACGGCAAGTTGAGTGCGGACCGTAACCCTGAATCGTACTCTTACTCGTCGAGAAAAATATCTGCAACATAAGACGTTGCAGCCGTGTAGGTCAGCATATTGAATATGCTGGCAAGTCACCAAAGAGAGGGGTGAAAATGTAATC
ATCTATACTATATGCATATATGGCAGGAGGGGTTGTAAGTTTTTAGCGTAAAGCAAATTTTCTCCTACAACAAGAGGGGCTAAAAGCAAAACATTACTACAAGGTTGGTTGTTAACGAGATGGTTCCGCCAACCAATTCTCGTACCCGAGTTGTCAGTAACACCCA
CATCAATATTATTATAATGGTGTTGAGAATTTCAGATAACTTCAGTTCCTTTGGCTCAAGTTGTCCATGACCGTGGACACGGCTAATCGATTAGGTTTGAGTACTCTGCAGAGTTTTGCACACGTTCCCCACAAGATTTGATCGCCTCCATGTATGTCCTCGCACT
TCAGGGTGTTTGAAGACCGGAAGATCAAAACATGGTCTTTCAACGGGTCCCTCTGAATCCCTGTCGGTGCCCATCCAAATCCTACCGTTCTTCTACATCTGCTAGCACCGCCTGTCCAGAGTCGCCACGTTGTCCAACCAAGCCAGAGCCCATAATGGCTTGTGGC
TGTGCAGGTAAGCCTTGGGTCTTGAAAATATCCGTCCGTCTCTTTGAGCCTGGGTGAAGCTTTCCGCAAGATGTCATGGCACGTCTCCAGCATCCCGGGCATCCACTGGTTTCTCCAGGGAGCCGATCAACCGTCCTTCACCCAGAGTTGCATTGCATCACAAGGT
CTTGAAAAGTCTTGACTTAACCGGTCTTGGTTATTAAATTATTCTCGCATCACTCGTGATAAACTCTCAACCAGAATCCCGTCTACTCACGCATAGCAATATGAAATTTGTCGTCCCGGGCCAAGTGACGGGGTTGTTGGATGCCTACCACATGATACTACAATAT
GTAACCATAATTTCCAAGTACCTACTCAGCATGCAATTGGGCAAAGAAAGGTGGAACTACCATGCATAGAAAACATAGGTGATAGTATGATCAAAGTGACTTGCCTGGTGATGTTGACGAAGAAGAATTATCGTTCTCGAGAAAATAACTTGATAGACTACTCGTC
ACTCTCCGATGAAATCTATATAACAAACATATCATTCACATAAGCACTCACACTAACAATCAAAACAAAAGAGAGAGCGAATAAGAATCCGAAGAACTTCAAATAAAACTAGTGAGTCTTCTTCTACATCAAACACTAAATAGTTTTTGTTCTAACTGAAAGTAAA
ACATTAAAATAACAGAGAACTAAGATATAAATTTAACTAAGATAAAATAAAGTATTTTTCATAAAACTAATTGAAAGTATTTTCAAATGGGAGTTGAAACCGTAGAGAAATCAATTGCAAGTTATTAGCAAACTTGAATTGATTTCACGATAAAAAATAAAATTAA
AATAAAAACTTGTTGAACACCTACTGTTTAACTAACAGAAACTAAACATAAACTTTCTGAAATATAAAAGAAATTAATTTAAAAACAACTAAAGAAAGAGACTTTAGTCACAATCCTAAAAGAGGTGAAACAGAAATTGTTTCACATGAAATAATGAGTTAAAATG
CTCAAACAATTCTGAAATTTTTACCACTGATAAACAAGATCACTAGTGATCAGTAGCAAAAGAATTAATTTAAAATCTATTTTTAAACTCCCAGAATAAGCAAAACAAGCTTTAAGTCAAATCTGATCTAACTAAATTTTTATAAATCCAAATATAGACAAATTAT
ATATTTTCGGAAACTACAAGAAAATTGTGATCTAACGCAAAACGAATCAGCATCATTGGACTTCTAGATCAAAAGTTATGGCCAAAACAAAATTGGAATTTTCTGTTTTTTGCAATTTAGACAGAAAAACTGAAGTTGACTAGCTAACAAATAGGGGTACACGTGG
CGCACTACTATAGGCTGCGGGGGGTGTTTGTTGCAACGTTTGGAGCAAACGGCCGAGGCTAACAAAAATTTTCGGTTAAAACATAAGTGAATTAAAACCGCCGGTTTTCTACTCTAAACCGAAGGGGTATACTAGGGATCTAATCTACACCATCTAAATATGATCT
AAGGGCTACTAAAGAAAAACAAAAAGAAACAGGAGGAGGGGATGGAGCCTTACCGTGGTTGGAGATGCTCCCGTGGCTGCTGGTGGCGAGGTGGAGGGGGGGGGCTCCGGTGGGGTGGGGAGGGGCCGGCGGGAGGAGGGGGAGTGGCAGGGGGCGGTGGGGCTCC
TGGGGGGGGAAGGGAGGCGAGGTGGAGGGGGTCTGCAGGGGGGGCGAGGGGGGGGGGAACTGCTGGTGTGCTGCTGCTCGTGGCAATGGCGATGGGGAGATGGAGAAAGGGCAGCAGGGGGCGGTGGAGGGGGTGCAGGAGGGTGCGGCAGGGGTGCCAGGGGGCG
AGGTGGGGCTGGGGCGAGGTGGATTCAGCTCCTGCCGAGCTCCTGTCAACAGAGAAGATGGCGACGGTGGCGCCGAGGCTACGGGCGGGGAAACGGAGATTTTTTTAGGGGAATGGAACGAGGAGAGGCGGGGCATTCTTATAGAGGCGACGGGAGGCGCCGGGAG
GAAGTATAGCTCGCGAATCCCGGAGGGGAAGCTTCTTGGGAAGCTTCTGCCATGGTACAGAAGGCAACGCTTGAGGTAGAAGAAGAAGGTGCGTTATGGGCCTGGTCTGTTTCCTAAGGTGGCCCAGGTACATTCCTAAAATAAGAGAGCTCTTTCCTTTTTTATT
AAATCAGGGGTTAATACTATTAAAAGCAAATGGAATATTCCTCGGAATATAGGGGTATAATATATTAAAATTTTCAGAAAAATAAATCCAAAAAGATGGGCATTTTTCCACTACCAAAATAAAAACTTCAGAAAAAATTATTTTCACAAAATGGCCTAAAAGATTT
ATTTTCTTTTGCAAATAATTTTCAAATGACCCTCTAGGTTTTAGGGTTCAAATAACTTTCAAAATGTCCATGGGTTTGAGGGTCATGTTCCTCCTCGCTTTTTTCTGTTTGACAGAAAGTATTTCCCGGCATTTCTTGCACGAAGAAAACAAGTAAAAATGCAAGA
GAATTCAAATGCAAATATCTCCGTTCAAATTCTTTATAGTTGAAGAAGTCATGTCATCTTCTCTCGTTGCTTTTAAAAGATTGAATTTGAACTCACCGGAGAAGGGGAAAGTCATTTTATTCCCTCTCATTCAAAAGTTTCGAAAAGTTTCAAATTCCACTCAAGT
TTCAATCACTCATTCAAACAAACAAACAATTCTAATAATTATTATTATTTTTTTTAACATTCCAAAATTTGGGATGTTACA

**Comment by jia-wu-feng** [comment]
@oushujun 
It seems that it is three sequences combined.
chr1H_3:293323..303934 , 
I found that it contains three sequences ：
chr1H_3:293323..296892_LTR#LTR/unknown
chr1H_3:296893..300367_INT#LTR/unknown
chr1H_3:300368..303934_LTR#LTR/unknown

**Comment by oushujun** [comment]
This is a good question. I have to go back to the codes to find out why it's reported differently. So here is the answer.
The screenshot is from the pass.list file, which header is this:
`#LTR_loc        Category        Motif   TSD     5_TSD 3_TSD       Internal        Identity      Strand  SuperFamily  TE_type     Insertion_Time`
eg.,
`M82_chr1:3661667..3667580       pass    motif:TGCA      TSD:TAT 3661664..3661666        3667581..3667583        IN:3662364..3666878     0.9900  -       Copia   LTR     388320`

Column 10 is superfamily and 11 is TE type (class), which are deterined by HMM profile matching.

For column 11,
 - The default is "NA" (no HMM alignment).
 - If all HMMs aligned to this candidates are LTR profiles, then column 11 will be assigned "LTR". 
 - If both LTR and nonLTR profiles are aligned, then col 11 will be assigned "mixture" and this entry will be determined "false" (column 2).

Column 10 is determined with the following rules:
 - The default is "unknown" (no HMM alignment), if there are alignments, depending on the number of gypsy and copia profiles:
 - $family="Gypsy" if ($gypsy>$copia and $copia/$gypsy<0.3);
 - $family="Copia" if ($copia>$gypsy and $gypsy/$copia<0.9);
 - if none of the matched profiles are specific to Copia or Gypsy, then column 10 remains "unknown".

Column 9 is determined with the following rules:
  - The default is "?" (no HMM alignment), if there are alignments, depending on the number of "+" and "-" directions:
  - $strand="+" if ($pos_strand>$neg_strand and $neg_strand/$pos_strand<0.4);
  - $strand="-" if ($neg_strand>$pos_strand and $pos_strand/$neg_strand<0.4);

So for "unknown NA", there's no rice LTR related HMM profiles matched to this candidate. For "unknown LTR", there are some rice LTR related HMM profiles matched, but we could not tell if this is a Copia or Gypsy.

For all LTR elements identified, the 5' LTR region, internal region, and 3' LTR region are separated into three sequences by default, as in your example.

Hope this helps!

Best,
Shujun

**Comment by jia-wu-feng** [comment]
Thanks, I will close the issue.
