### ISSUE TITLE
About the proportion of the "unkonwn" item in the genome (".superfam.size.list" file).

### ISSUE THREAD

**Issue by wensulin93** [oushujun/LTR_retriever#127]
hello @oushujun

I noticed that ".superfam.size.list "has a large proportion of" unkonwn "items, I am surprised by this "unknown" definition; Are they LTR retrotransposons or some other unknown piece of DNA? Because now I want to explore the proportion of LTR retrotransposons in the genome, if the proportion of "unknown" is small, it may be negligible; But it reached more than 10%, so I think it's worth considering. Therefore, I wonder if this "unkonwn" is  LTR retrotransposons? Can we say that in the following example, LTR retrotransposons make up 44.22% of the genome?

![image](https://user-images.githubusercontent.com/63379795/179335786-4209c5dc-f3aa-4aab-860b-26d653a2659b.png)

**Comment by oushujun** [comment]
Hi @wensulin93,

Yes, these are considered LTR sequences. The LTR elements with unknown superfamily is either lacking coding information that can definitely classify them into either the Copia and Gypsy superfamilies or having multiple coding regions that belong to both Copia and Gypsy superfamilies. Either situation we could not confidently classify them. Of course, there are other superfamilies (eg. Bel-Pao) that are not considered in the classification here.

Hope this helps!

Best,
Shujun

**Comment by wensulin93** [comment]
@oushujun 
你好，区神，我想让您作为我论文的审稿人，不知道你有没有兴趣？我询问了你老板，他直接推荐你为审稿人~！🤣
