### ISSUE TITLE
How to run LTR.identifier.pl independently?

### ISSUE THREAD

**Issue by xiekunwhy** [oushujun/LTR_retriever#128]
Hi,

I have two questions,

1) The whole LTR_retriever pipeline on single computer node is too slow for large genome, so I want to run some steps parallelizing. But I found that I can not get Alignment regions when I run LTR.identifier.pl independently, do you know why?
Here are datas and command line I used, all Alignment regions in test.defalse are 0, 0, 0, 0
https://drive.google.com/file/d/16NaLX5waQjFE25Vzzkl41cWnus22NUf1/view?usp=sharing

2) In LTR.identifier.pl, start..end are used as scn hash keys (line 89 and line 90), will this cause problems when start...end are the same but from difference chromosomes?

Best regards,
Kun

**Comment by xiekunwhy** [comment]
The question 1 has been solved, .../ltr_retriever/bin should be ltr_retriever/bin/.

**Comment by oushujun** [comment]
Hi Kun,

Thank you for trying to acclerate LTR_retriever! For the second question it's possible that two LTR candidates from different chromosomes have the same start and end, but this is highly unlikely. Assuming two chromosomes are both 10Mb long, having an identical coordinate between two regions is 1/10M * 1/10M by chance (= 1/100M).

Please let me know how it goes!

Best,
Shujun

**Comment by xiekunwhy** [comment]
Thank you for your reply, I will try to make some modification to aviod this problem, some genome I am annotating are very large.

I found that in proMask step, the protein database only include plant protein sequences, so can I use this pipeline to annotate animal genomes?

Best,
Kun

**Comment by oushujun** [comment]
You expect to have one mismatched candidate in 100 million candidates. I
don't think you will have that many of LTR candidates in a genome.

For the plant protein database, you may provide an animal version but the
default won't hurt that much. I have been lagging to find an animal
version. If you found one please let me know.

Thanks,

Shujun
