### ISSUE TITLE
For genus-level  TE-annotation

### ISSUE THREAD

**Issue by LeeYEAH2** [oushujun/LTR_retriever#131]
Dear Shujun,
  LTR_retriever is a great tool to combine harvest&finder results, but the TE_annotation procedure could only classify Ltrs as Copia/Gypsy/unknown, I am wondering if it's possible to classify those Ltrs into genus level e.g. CRM/Galadriel for Gypsy.
  Do you have any idea on where to modify the code to fulfill this need? maybe the annotate_TE.pl part?
With regards.

**Comment by oushujun** [comment]
Yes: https://academic.oup.com/hr/article/doi/10.1093/hr/uhac017/6532211?login=true

**Comment by LeeYEAH2** [comment]
The work of LTR_retriever and TEsorter really helps. Thanks a lot .
