### ISSUE TITLE
too many LTR/unknown and most of LTR/unknown are classified as LTR/Gypsy

### ISSUE THREAD

**Issue by shiyi-pan** [oushujun/LTR_retriever#132]
Hi, I want to detecte LTR and calculate LAI with LTR_retriever in soybean.  
I used zhonghuang 13 , a soybean reference genome, as a test and found the proportion of LTR detected by LTR_retriever was  inconsistent with zhonghuang 13 reported in the literature.

here is  the proportion of LTR detected by LTR_retriever:

 full    left    right   total    all      bps     percent     class      subclass        note
028800  018609  017819  047229  0137397  111040972  11.13705    LTR         Copia            LTR
026820  026444  038316  059504  0221280  188797176  18.93575    LTR         Gypsy            LTR
029850  032206  027784  059983  0241037  105969966  10.62844    LTR         unknown          LTR

here is the proportion of LTR reported in the literature:

![image](https://user-images.githubusercontent.com/58731075/183810253-4ea575d6-9864-416a-80b3-bc5cc4342626.png)

This is the opposite of what happens in the Issue 51, the sum of the proportion of gypsy and unknown identified by LTR_Retriever is just similar to the proportion of Gypsy reported in the literature.

Could you give me some advise? Thank you very much.

**Comment by oushujun** [comment]
Duplicated #127 and #51.
You may try TEsorter or machine-learning-based classifiers to further classify the results.

Shujun
