### ISSUE TITLE
No candidate is found in the file(s) you specified.

### ISSUE THREAD

**Issue by cherryDAP** [oushujun/LTR_retriever#135]
After using LTR-FINDER to get ocu.finder.scn, run LTR_retriever.

LTR_retriever -threads 10 -genome new.genome.fasta -infinder ocu.finder.scn.

But I get the title error:      ERROR: No candidate is found in the file(s) you specified.

**Comment by oushujun** [comment]
Can you post a couple of lines of the file "ocu.finder.scn"? Thanks

**Comment by cherryDAP** [comment]
A few lines of code for the file "ocu.finder.scn" are as follows, and upload ocu.finder.scn under the code


Program    : LTR_FINDER
Version    : 1.07

Predict protein Domains 0.025 second
>Sequence: fra_scf_24 Len:161586
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
[ 1]	fra_scf_24	15647-22374	331,331	6728	CCTTT	N-N	15978-15992	N-N	N-N	N-N	N-N	-	6	0.5,0.5	0.979
[ 2]	fra_scf_24	23304-27881	336,336	4578	AATAT	N-N	23640-23654	N-N	N-N	N-N	N-N	-	6	0.486,0.557	1

Predict protein Domains 0.007 second
>Sequence: scf_1309 Len:32478
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
[ 1]	scf_1309	4096-9570	603,607	5475	CTTTG	N-N	8948-8962	N-N	N-N	N-N	N-N	+	6	0.543,0.443	0.988

Predict protein Domains 0.034 second
>Sequence: scf_1302 Len:321473
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
[ 1]	scf_1302	171712-179314	823,823	7603	CCTT	N-N	172535-172549	N-N	N-N	N-N	N-N	-	6	0.514,0.557	0.995

Predict protein Domains 0.000 second
>Sequence: scf_1305 Len:9455
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
No LTR Retrotransposons Found

Predict protein Domains 0.000 second
>Sequence: scf_1498 Len:2279
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
No LTR Retrotransposons Found

Predict protein Domains 0.039 second
>Sequence: scf_1714 Len:164517
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
[ 1]	scf_1714	9763-17883	561,561	8121	CTAAA	N-N	10327-10341	N-N	N-N	N-N	N-N	-	6	0.486,0.486	0.995
[ 2]	scf_1714	33035-37925	419,422	4891	AAGT	N-N	37412-37426	N-N	N-N	N-N	N-N	+	6	0.414,0.457	0.898
[ 3]	scf_1714	60801-74350	234,128	13550	AAAAT	N-N	74134-74148	N-N	N-N	N-N	N-N	+	6	0.714,0.4	0.798
[ 4]	scf_1714	61043-66788	163,163	5746	AAAA	N-N	66572-66586	N-N	N-N	N-N	N-N	+	6	0.414,0.414	0.951

Predict protein Domains 0.000 second
>Sequence: scf_956 Len:3987
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
No LTR Retrotransposons Found

Predict protein Domains 0.000 second
>Sequence: scf_1206 Len:175
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
No LTR Retrotransposons Found

Predict protein Domains 0.034 second
>Sequence: scf_955 Len:142851
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
[ 1]	scf_955	3073-8688	638,638	5616	ACTTT	N-N	7994-8008	N-N	N-N	N-N	N-N	+	6	0.529,0.571	0.939
[ 2]	scf_955	16583-34716	168,163	18134	N	N-N	34504-34518	31109-31594	N-N	N-N	N-N	+	6	0.429,0.471	0.85

Predict protein Domains 0.041 second
>Sequence: scf_1209 Len:155082
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
[ 1]	scf_1209	74620-82005	971,970	7386	TATA	N-N	81021-81035	N-N	N-N	N-N	N-N	+	6	0.5,0.471	0.999
[ 2]	scf_1209	107997-116323	617,617	8327	CATA	N-N	115654-115668	N-N	N-N	N-N	N-N	+	6	0.557,0.543	1
[ 3]	scf_1209	140711-146669	725,725	5959	GTGGC	N-N	145892-145906	N-N	N-N	N-N	N-N	+	6	0.514,0.514	1

Predict protein Domains 0.014 second
>Sequence: fra_scf_118 Len:84349
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
[ 1]	fra_scf_118	2740-7205	267,267	4466	TTATG	N-N	3046-3060	N-N	N-N	N-N	N-N	-	6	0.6,0.486	0.989

Predict protein Domains 0.032 second
>Sequence: fra_scf_110 Len:255309
index	SeqID	Location	LTR len	Inserted element len	TSR	PBS	PPT	RT	IN (core)	IN (c-term)	RH	Strand	Score	Sharpness	Similarity
[ 1]	fra_scf_110	220093-227182	381,381	7090	TATATA	N-N	226787-226801	223604-224029	N-N	N-N	N-N	+	7	0.571,0.543	0.995

Predict protein Domains 0.000 second

[ocu.finder.scn.txt](https://github.com/oushujun/LTR_retriever/files/9584417/ocu.finder.scn.txt)

**Comment by cherryDAP** [comment]
Is there something wrong with my input file, but I am running ltr_finder with default parameters
$ ltr_finder -C -w 2 new.genome.fasta >ocu.finder.scn

**Comment by oushujun** [comment]
It looks good to me. Can you rerun it and double check if the genome and
LTR candidates are from the same version of sequence?

**Comment by cherryDAP** [comment]
Thank you for your suggestion. According to your suggestion, I re-calculated ltr_finder and LTR_retrieverd, and also determined that the genome is the same genome. But unfortunately still the same result.
![edcc29915def4a0c8019eefe1b678c4](https://user-images.githubusercontent.com/110672898/191495297-7110eb42-b1bf-4be2-a53c-cb0c4e739888.png)

**Comment by oushujun** [comment]
Can you test on an Arabidopsis genome or something small and quick?

Shujun

**Comment by oushujun** [comment]
@cherryDAP any luck?
