### ISSUE TITLE
Are LTRs (insertion time of 0) the likely cause of somatic variation?

### ISSUE THREAD

**Issue by Wenwen012345** [oushujun/LTR_retriever#141]
Hi @oushujun 

My research topic is about "somatic variation", and I will finish my dissertation recently. Now there is a question: I noticed that you said in the previous answer that the insertion time of LTR is "0" which means that it has been inserted recently or is currently being inserted （https://github.com/oushujun/LTR_retriever/issues/44#issuecomment-843035352）. In our concept, we believe that LTR is an important factor causing somatic variation. Then I would like to ask, could these LTRs with an insertion time of 0 be the main factor causing somatic variation? Maybe we can think of them as active LTRs? Thanks!

Note: Somatic mutations refer to mutations that occur in somatic cells other than sex cells. The vast majority do not cause genetic changes in offspring. Includes phenotypic, cytologic or molecular variants.

**Comment by oushujun** [comment]
It's likely a cause, but whether it is the main cause or just a contributing factor, I don't know, and it will be interesting to find out. Intact LTR elements with 0 yr of age suggest they are pretty young, but as I said in the previous post, we don't know whether it was inserted yesterday or a thousand years ago. It suggests recent activity but IS NOT evidence of recent activity. You need to sequence the genome from multiple time points or tissues, and if you find insertional variation, this is evidence of recent activity.

**Comment by Wenwen012345** [comment]
> It's likely a cause, but whether it is the main cause or just a contributing factor, I don't know, and it will be interesting to find out. Intact LTR elements with 0 yr of age suggest they are pretty young, but as I said in the previous post, we don't know whether it was inserted yesterday or a thousand years ago. It suggests recent activity but IS NOT evidence of recent activity. You need to sequence the genome from multiple time points or tissues, and if you find insertional variation, this is evidence of recent activity.

Hello！ @oushujun 

Thank you very much for taking the time to solve these problems for me or everyone during this period of time. And a lot of your help. I don't know how to thank you enough. I know you are very busy, really appreciate you taking the time out of your busy schedule to solve some of our problems. I hope that if you return to China, I can invite you to dinner or have the opportunity to express my gratitude to you in person. 

Sorry I don't like to use names very much in this forum, I prefer to be anonymous. 

Anyway thank you again!
Thank you and best regards. Yours sincerely,
Wen,Sulin
