### ISSUE TITLE
LTR_retriever warning

### ISSUE THREAD

**Issue by fafuyyk** [oushujun/LTR_retriever#142]
Dear OuShujun

Hello, I use ltr_finder to identify LTR, and use LTR_retriever to correct it. But in my result, there are two kinds of warnings, I can't understand this problem, I want to consult.

Warning one:

Warning: [blastn] Query_28745 chr23.1:13897.. : Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options

Warning two:
【Warning】 The identity drops below the safe limit. Instead, identity of 92% will be used for LAI adjustment.

I would like to ask if the meaning of these alerts has affected my results

**Comment by oushujun** [comment]
Warning one says one sequence is invalid. If this reportes only once, it
should be ok

Warning two generated during LAI calculation. It says the overall LTRs are
older than the allowed limit. Maybe your genome has very old LTRs or the
quality is not good.

Shujun
