### ISSUE TITLE
RE: Masking LTR

### ISSUE THREAD

**Issue by Malabady** [oushujun/LTR_retriever#144]
Hey
I want to confirm that the LTR library (*.fa.LTRlib.fa) is the correct library file that I can use with RepeatMasker to mask the genome. If this is not the correct library file, what is the correct one? 

Best,

**Comment by oushujun** [comment]
Yes this is the correct file.

Shujun

**Comment by Malabady** [comment]
Many thanks.

From: Shujun Ou ***@***.***>
Date: Tuesday, January 24, 2023 at 10:40 PM
To: oushujun/LTR_retriever ***@***.***>
Cc: Magdy S Alabady ***@***.***>, Author ***@***.***>
Subject: Re: [oushujun/LTR_retriever] RE: Masking LTR (Issue #144)
[EXTERNAL SENDER - PROCEED CAUTIOUSLY]
Yes this is the correct file.

Shujun
