### ISSUE TITLE
How to discover "sequencing gaps" in genome assemblies.

### ISSUE THREAD

**Issue by Wenwen012345** [oushujun/LTR_retriever#146]
Hello shujun 

LTR_Retriever is a great tool and we have used it a lot in our research recently. Based on LTR_Retriever we were able to develop some high-resolution IRAP molecular markers, and then follow-up is planning to sequence the genomes of the species we study. This tool can help us to well resolve the LTRs in the genome. 

The above is off topic. Recently, our paper feedback came back, and the reviewers questioned some long genes containing transposons (such as the picture below). He thinks there might be a sequenced GAP. But we were puzzled by the method of finding sequenced GAPs. So I want to ask you for advice. The main question I want to ask is: If the sequences of these genes are extracted, is it possible to directly observe whether these sequences have sequenced GAP (should be represented by "N")?  Does this count as direct evidence for the existence of these long genes and the Absence of sequenced GAP? Also, it may not be convenient for us to do PCR now. 

Attached below are the sequence files of several genes in the figure. No "N" has been found for the time being. Is it possible to explain that they have no sequenced GAP？

![微信截图_20230222214227](https://user-images.githubusercontent.com/63379795/220644997-38f6526c-486d-4937-a196-85d728bf928b.png)

 sequence files：
[mulID.zip](https://github.com/oushujun/LTR_retriever/files/10804600/mulID.zip)

**Comment by Wenwen012345** [comment]
Hello, maybe I thought of a way. You can BLAST the DNA sequence on NCBI. Generally speaking, if these genes really exist, BLAST will have the result of homologous alignment. And if the BLAST results are visualized, there should be a reasonable correspondence, and the "empty part" should be the part where the transposon is inserted.

**Comment by oushujun** [comment]
Hello,

I am glad LTR_retriever is helping you to find our biologically meaningful markers! Your question is a bit off topic, but I think your proposed ways (PCR, no 'N', BLAST) should work especially with multiple evidence combined.

Best,
Shujun

**Comment by Wenwen012345** [comment]
Thanks! This guy tried it. The manuscript is somewhat related to graduation, so the guy has carefully considered this issue.
