### ISSUE TITLE
ask for help? panLTR

### ISSUE THREAD

**Issue by fafuyyk** [oushujun/LTR_retriever#147]
Hello!
I used LTR_Retriver to identify multiple genomic LTRs, but I want to do panTE analysis now, but I'm running out of time. I wonder if there is any way to identify species-specific LTR families. We failed to split the subgenome using subphaser, so we could not use shuphaser for identification, but we split the subgenome using the method of tree building. What advice do you have for identifying species-specific LTR families?

**Comment by oushujun** [comment]
You may try [panEDTA](https://github.com/oushujun/EDTA/releases/tag/v2.1.0) which contains annotation of LTRs.

Best,
Shujun
