### ISSUE TITLE
Running Ltr_retriever...Died at /app/RepeatModeler-2.0.4/LTRPipeline line 693.

### ISSUE THREAD

**Issue by ShirelyI** [oushujun/LTR_retriever#148]
Dear shujun:
Thanks for your software.I met some wrong messages when I ran repeatmodeler,the log is as follows :

LTR Structural Analysis
=======================
Running LtrHarvest...     : 00:00:09 (hh:mm:ss) Elapsed Time
Running Ltr_retriever...Died at /biodb/labs/liuhuanzhang/app/RepeatModeler-2.0.4/LTRPipeline line 693.
LTRPipeline Time: 00:02:09 (hh:mm:ss) Elapsed Time

Software were install manually :LTR_retriever-2.9.0 , RepeatModeler-2.0.4 , rmblast-2.13.0 , genometools-1.6.2  .
The results compare to normal  Ltr_retriever running were different. If I run Ltr_retriever  seperately ,I'm not sure which file should be the inputfile after -inharvest?
I tried to find solutions but found no answers.Could you please help me with this question?
Looking forward to your reply.
Best wishes,
Lily

**Comment by oushujun** [comment]
Seems like this is a repeatmodeler2 issue. Please refer to the LTR_retrieve documentation regarding the input files.

Best,
Shujun

**Comment by ShirelyI** [comment]
Hi Shujun,
Ltr_retriever was installed by conda before, it works after manually installed .
Thanks for your reply.
Best wishes,
Lily
