### ISSUE TITLE
No tbl file issue

### ISSUE THREAD

**Issue by wrengs** [oushujun/LTR_retriever#149]
Dear @oushujun ,

While running LTR_retriever previously successfully on multiple genomes, I am currently experiencing an issue similar to Issue #134 

All seems to run fine up to a point where the following error occurs:
grep: Genome_ch01-12.fasta.tbl: No such file or directory

Afterwards, no LAI is generated.
Attached is the nohup file
[20230309_nohup_LTR_retriever.txt](https://github.com/oushujun/LTR_retriever/files/10940476/20230309_nohup_LTR_retriever.txt)

I also noticed that a RepeatMasker generated folder remained present, which was not the case for previous tried genomes.

Any suggestions how to move forward from here?

Many thanks in advance!
Kind regards,
Willem

**Comment by oushujun** [comment]
RepeatMasker is not finished in annotating your genome with the LTR library. You may annotate it your own and calculate LAI with the LAI script. 

Alternatively, you may try giving less CPUs to LTR_retriever since RepeatMasker tends to overutilize CPU and may trigger job termination.

Shujun

**Comment by oushujun** [comment]
Hi Willem,

Did you see the file 20000.LAI.LTR.ava.out get any updates? With 8 cores it
should take a while for a 1.1G genome

Shujun

**Comment by wrengs** [comment]
Dear Shujun, 

The run was started on the 14th and the last update to 20000.LAI.LTR.ava.out was on the 19th. 

All the best,
Willem

**Comment by wrengs** [comment]
Dear Shujun,

In parallel to the run that I started on the 14th of March (described above), I re-started from scratch with suggested less threads using another cluster on the 17th also.
The run started on the 17th finished (<5 days for 1.1G genome) without issues, whereas the run started on the 14th seems stuck still.

I guess the run (14th) might have been stopped due to intensive usage of that specific cluster, in combination with possible overutilization by RepeatMasker? Alternatively, some files might have been corrupted or causing issues as due to the initial crash (RepeatMasker folder remained present). 
Perhaps good for future users to keep an eye on.

Anyway, thank you kindly for your responsiveness and suggestion.
I will close with comment.

Kind regards,
Willem
