### ISSUE TITLE
LAI is not applicable on the current genome assembly

### ISSUE THREAD

**Issue by yilunhuangyue** [oushujun/LTR_retriever#150]
Hello, I want to count LAI of a plant genome and got the error message:
【Error】Intact LTR-RT content (0%) is too low for accurate LAI calculation (min 0.1% required)
 【Error】 Total LTR sequence content (0%) is too low for accurate LAI calculation (min 5% required)
It is very wired because there are 33% LTRs in genome.fa.tbl file and there are also records in genome.fa.pass.list

The command used was as follows:
ltr_finder -D 20000 -d 1000 -L 7000 -l 100 -p 20 -C -M 0.80 genome.fa > out.finder.scn
LTR_retriever -genome genome.fa  -infinder out.finder.scn -threads 20

 Thank you very much for any help

**Comment by oushujun** [comment]
Make sure you use the LTR annotation correspond to your genome fasta file.
You may want to use fasta.mod Instead of fasta if the annotation is
generated by LTR_retriever.

Best,
Shujun

**Comment by yilunhuangyue** [comment]
Sorry for the late reply. Yes, the annotation file was generated by LTR_retriever. I am sure I used the corresponding genome file and I still got the same error when using fasta.mod.

Very appreciate for your quick reply

**Comment by oushujun** [comment]
You may want to manually check if the sequnce IDs are matching between the fasta file used and the annotation files. Also, although should not related to this issue, you may also want to add LTRharvest outputs to LTR_retriever for calculation of LAI.

Thanks,
Shujun
