### ISSUE TITLE
conda install errors

### ISSUE THREAD

**Issue by xiekunwhy** [oushujun/LTR_retriever#151]
Hi,

I got errors when install using conda, do you know why?
![image](https://user-images.githubusercontent.com/17738229/230523179-fb84c1dd-3d4f-470a-9a40-90e62e82aa9d.png)

Best,
Kun

**Comment by oushujun** [comment]
As it suggested, the RepeatMasker installation is corrupted. You may try to
create a new env to install them fresh.

Best,
Shujun
