### ISSUE TITLE
I can´t install LTR_retriever via conda

### ISSUE THREAD

**Issue by jplondono14** [oushujun/LTR_retriever#152]
I have unsuccessfully tried to create a conda environment in order to download and use LTR_retriever. However this detailed error appears constantly. I just used this command:

conda create -n ltr_retriever
source activate ltr_retriever
conda install -c bioconda ltr_retriever

Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... ^MBuilding graph of deps:   0%|          | 0/15 [00:00<?, ?it/s]^MExamining libgomp:   0%|          | 0/$
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (perl-text-soundex):

  - ltr_retriever -> cd-hit
  - ltr_retriever -> perl
  - ltr_retriever -> perl-text-soundex -> perl[version='5.22.0.*|>=5.26.2,<5.26.3.0a0|>=5.32.1,<5.32.2.0a0|>=5.32.1,<6.0a0',build=*_perl5]

I really would appreciate some help

**Comment by oushujun** [comment]
Hello,

Sorry for the incovenience. I am currently updating the conda recipe to prepare for the v2.9.3 release, so the conda installation is still a bit funky. You may use the [step-by-step](https://github.com/oushujun/LTR_retriever#step-by-step-using-conda) annotation approach for the moment. Please let me know if this works or not.

Best,
Shujun

**Comment by oushujun** [comment]
Hello,

The conda recipie has been updated. You should be able to install normally now. Please let me know if you encounter any issues. Thanks!

Shujun

**Comment by oushujun** [comment]
Hello,

You may try to specify the version by `conda install -c bioconda ltr_retriever=2.9.4`, otherwises you may clean up the cached packages and retry. You may also try on a different server and see if it's the issue of Os or the package recipe.

Shujun
