### ISSUE TITLE
awk: cannot open N02.fa.retriever.scn.extend.fa.rexdb.cls.tsv

### ISSUE THREAD

**Issue by renmiaozhen** [oushujun/LTR_retriever#155]
When I run the LTR_retriever : `/software/LTR_retriever-2.9.5/LTR_retriever -genome N02.fa -inharvest N02.fa.rawLTR.scn -threads 10 -u 7.3e-9`, I receive some warning information: 

1. awk: cannot open N02.fa.retriever.scn.extend.fa.rexdb.cls.tsv (No such file or directory); 
2. Command line argument error: Argument "query". File is not accessible:  'N02.fa.ltrTE.stg3.cln'
cat: N02.fa.ltrTE.stg3.line.out: No such file or directory
cat: N02.fa.ltrTE.stg3.dna.out: No such file or directory
cp: cannot stat 'N02.fa.ltrTE.stg3.cln': No such file or directory
Command line argument error: Argument "query". File is not accessible:  `N02.fa.ltrTE.stg3.cln.clean'
ERROR: Please specify the BLAST result!
3. ERROR: No such file or directory at /software/LTR_retriever-2.9.5/bin/output_by_list.pl line 37.
   ERROR: No such file or directory at /software/LTR_retriever-2.9.5/bin/output_by_list.pl line 37.
    Wed 12 Jul 2023 11:19:12 AM CST Retained clean sequence: 0
4. ERROR: 6493 intact LTR-RTs have found, but the pre-library file N02.fa.ltrTE is empty;
5. awk: cannot open N02.fa.retriever.scn.extend.fa.rexdb.cls.tsv (No such file or directory)

Although received so much error information, the final result "N02.fa.pass.list" was not empty. 
Can I use this result? 
Do any suggestions give me?

**Comment by oushujun** [comment]
Hello,

Something is wrong. Can you share the original status output? It will be helpful to identify the error.

Thanks,
Shujun

**Comment by oushujun** [comment]
Hello,

Can you update to [cf58800](https://github.com/oushujun/LTR_retriever/commit/cf58800573409e2eaad7b309d10674eece6ab2b7) and try again? 

I don't understand why you ran LTR_retriever twice.

Thanks,
Shujun

**Comment by oushujun** [comment]
@renmiaozhen any luck?

**Comment by oushujun** [comment]
This bug (#154) should be fixed in the latest version. Please update and try again. Please reopen the issue if you find it not fixed. Thank you!

Shujun
