### ISSUE TITLE
LOC list New_genome.nextpolish.exceptChl.FINAL.fa.retriever.scn.full is empty

### ISSUE THREAD

**Issue by cutykaka** [oushujun/LTR_retriever#157]
Hi shujun,

I tried to run LTR_retriever, but I met an error like below.

##########################
##########################

Contributors: Shujun Ou, Ning Jiang

For LTR_retriever, please cite:

        Ou S and Jiang N (2018). LTR_retriever: A Highly Accurate and Sensitive Program for Identification of Long Terminal Repeat Retrotransposons. Plant Physiol. 176(2): 1410-1422.

For LAI, please cite:

        Ou S, Chen J, Jiang N (2018). Assessing genome assembly quality using the LTR Assembly Index (LAI). Nucleic Acids Res. 2018;46(21):e126.

Parameters: -genome New_genome.nextpolish.exceptChl.FINAL.fa -inharvest New_genome.nextpolish.exceptChl.FINAL.fa.rawLTR.scn -threads 16

Tue Aug 29 01:34:29 KST 2023    Dependency checking: All passed!

                                Previous LTR_retriever results found, backed up to LTRretriever-pre08-29-23_0134

Tue Aug 29 01:34:42 KST 2023    LTR_retriever is starting from the Init step.
Tue Aug 29 01:35:02 KST 2023    Start to convert inputs...
Use of uninitialized value $seq_ID in exists at /BiO/Program/LTR_retriever/bin/get_range.pl line 123, <TBL> line 668.
Argument "ID=repeat_region1" isn't numeric in numeric ge (>=) at /BiO/Program/LTR_retriever/bin/get_range.pl line 133, <TBL> line 668.
Argument "." isn't numeric in numeric ge (>=) at /BiO/Program/LTR_retriever/bin/get_range.pl line 133, <TBL> line 668.
Argument "?" isn't numeric in subtraction (-) at /BiO/Program/LTR_retriever/bin/get_range.pl line 140, <TBL> line 668.
Illegal division by zero at /BiO/Program/LTR_retriever/bin/get_range.pl line 152, <TBL> line 668.
Warning: LOC list New_genome.nextpolish.exceptChl.FINAL.fa.retriever.scn.full is empty.
                                Total candidates: 639510
                                Total uniq candidates: 0

Tue Aug 29 01:35:25 KST 2023    Module 1: Start to clean up candidates...
                                Sequences with 10 missing bp or 0.8 missing data rate will be discarded.
                                Sequences containing tandem repeats will be discarded.

        Usage: perl cleanup.pl -f sample.fa [options] > sample.cln.fa 
        Options:
                -misschar       n       Define the letter representing unknown sequences; case insensitive; default: n
                -Nscreen        [0|1]   Enable (1) or disable (0) the -nc parameter; default: 1
                -nc             [int]   Ambuguous sequence len cutoff; discard the entire sequence if > this number; default: 0
                -nr             [0-1]   Ambuguous sequence percentage cutoff; discard the entire sequence if > this number; default: 1
                -minlen         [int]   Minimum sequence length filter after clean up; default: 100 (bp)
                -cleanN         [0|1]   Retain (0) or remove (1) the -misschar taget in output sequence; default: 0
                -trf            [0|1]   Enable (1) or disable (0) tandem repeat finder (trf); default: 1
                -trf_path       path    Path to the trf program
        
Tue Aug 29 01:35:25 KST 2023    0 clean candidates remained

cp: cannot stat ‘New_genome.nextpolish.exceptChl.FINAL.fa.retriever.scn.adj’: No such file or directory
Tue Aug 29 01:35:25 KST 2023    No LTR-RT was found in your data.

Tue Aug 29 01:35:25 KST 2023    All analyses were finished!

I think that the step which generate *.scn.full file doesn't work.
Could you give me solution for this error message?

**Comment by oushujun** [comment]
Please simplify your seq IDs manually and try again.

Thanks,
Shujun

**Comment by cutykaka** [comment]
Thank you for the quick response.
However, I've already proceeded with the analysis using a fasta file that contains very simple seqIDs.
My genome.fasta file has headers designated as Chr1, Chr2, Chr3, etc., so what could possibly be the issue

**Comment by oushujun** [comment]
#154
