### ISSUE TITLE
fa.mod.nmtf.pass.list is empty

### ISSUE THREAD

**Issue by 44314474** [oushujun/LTR_retriever#159]
Hello! When i used LTR_retriever, the output files:fa.mod.nmtf.pass.list and fa.mod.defalse are empty.

The code is :LTR_retriever -genome ./Gallus_gallus.fa -inharvest /public/home/wml/Repeat/02.insert_time/Gallus_gallus/02.LTR_harvest/Gallus_gallus.fa.harvest.combine.scn -infinder /public/home/wml/Repeat/02.insert_time/Gallus_gallus/01.LTR_finder/Gallus_gallus.fa.finder.combine.scn -threads 40

These are the messages that generated :Sun Nov 26 16:50:12 CST 2023    Dependency checking: All passed!
Sun Nov 26 16:50:16 CST 2023    LTR_retriever is starting from the Init step.
Sun Nov 26 16:50:28 CST 2023    The longest sequence ID in the genome contains 19 characters, which is longer than the limit (13)
                                Trying to reformat seq IDs...
                                Attempt 1...
                                Attempt 2...
Sun Nov 26 16:50:40 CST 2023    Seq ID conversion successful!

Sun Nov 26 16:50:50 CST 2023    Start to convert inputs...
                                Total candidates: 3240
                                Total uniq candidates: 3240

Sun Nov 26 16:51:04 CST 2023    Module 1: Start to clean up candidates...
                                Sequences with 10 missing bp or 0.8 missing data rate will be discarded.
                                Sequences containing tandem repeats will be discarded.

Sun Nov 26 16:51:04 CST 2023    3165 clean candidates remained

Sun Nov 26 16:51:04 CST 2023    Modules 2-5: Start to analyze the structure of candidates...
                                The terminal motif, TSD, boundary, orientation, age, and superfamily will be identified in this step.

Invalid value for shared scalar at /public/home/wml/miniconda3/envs/genome_annotation/share/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line 331.
Sun Nov 26 16:52:35 CST 2023    Intact LTR-RT found: 0

cp: cannot stat ‘Gallus_gallus.fa.mod.retriever.scn.adj’: No such file or directory
Sun Nov 26 16:52:35 CST 2023    No LTR-RT was found in your data.

Sun Nov 26 16:52:35 CST 2023    All analyses were finished!

But i have no idea to deal with this :Invalid value for shared scalar at /public/home/wml/miniconda3/envs/genome_annotation/share/LTR_retriever/bin/LTR.identifier.pl line 114, <ANNO> line 331.

Any help or suggestions would be greatly appreciated.
Thanks!

**Comment by oushujun** [comment]
Hello,

Please update to the latest GitHub version and run again. The current conda
version has an identified bug reported in Issue.

Shujun

**Comment by oushujun** [comment]
#153
