### ISSUE TITLE
LTR_retriever failed to generate a file -  data passing in a multithreaded run

### ISSUE THREAD

**Issue by cyycyj** [oushujun/LTR_retriever#160]
Dear Shujun,

I have encountered a problem with the LTR_retriever program, and Robert @rmhubley pointed out it is related to data passing in a multithreaded run. According to my sight, it is widely happened around myself. Please kindly check the problem detail in RepeatModeler issue here: https://github.com/Dfam-consortium/RepeatModeler/issues/230. Thank you for your help.

Note: I installed LTR_retriever and other dependencies of RepeatMasker through conda.

**Comment by oushujun** [comment]
Hi Andrew,

Please update your LTR_retriever using the github version. See more here: https://github.com/oushujun/LTR_retriever/issues/153

Best,
Shujun

**Comment by cyycyj** [comment]
Dear Shujun,

Thanks a lot! Now the bugs have been solved.
