### ISSUE TITLE
A reviewer's comment related to the setting of mutaion rate

### ISSUE THREAD

**Issue by zhdang** [oushujun/LTR_retriever#164]
Dear Shujun,

We utilized the LTR_retriever to estimate the insertion time of LTR-RTs in our studied genome and other reference genomes. Regarding the analysis, the reviewers have raised a concern: "The mutation rates of the selected species are different. How are the mutation rates for these species set in the analysis of LTR insertion times?" Would you please suggest to us how we should address or respond to this issue? You mentioned setting the mutation rate using the parameter -miu in a previous issue. Is the mutation rate for specific species included in the results of the LTR_retriever analysis? Do we need to set the -miu parameter when analyzing specific species, or is it ok to use the same default parameters?

Looking forward to your reply.

Best regards,
Zhenhua Dang

PS: Our analysis is shown below; the red line represents our studied species. We mentioned a 0.3 million years ago (mya) insertion of LTR-RTs in the genome. The LAI of the genome is 13.1.

![LTR](https://github.com/oushujun/LTR_retriever/assets/48577014/8959a412-e09e-40af-a928-1b43c3903060)
![LTR Assembly Index](https://github.com/oushujun/LTR_retriever/assets/48577014/1e3df343-637f-42ce-bead-b0a9ab014e65)

**Comment by oushujun** [comment]
Yes, the default mutation rate is from rice. You may specify a mutation rate of your species to be more accurate.

Thanks,
Shujun

**Comment by zhdang** [comment]
Hi Shujun,
Thank you very much for your reply, I will try this.
Cheers,
Zhenhua
------------------------------------------------------------------
发件人：Shujun Ou ***@***.***>
发送时间：2024年3月15日(星期五) 03:08
***@***.***>
***@***.***>; ***@***.***>
主　题：Re: [oushujun/LTR_retriever] A reviewer's comment related to the setting of mutaion rate (Issue #164)
Yes, the default mutation rate is from rice. You may specify a mutation rate of your species to be more accurate.
Thanks,
 Shujun
