### ISSUE TITLE
Extract intact Ltrs to fasta 

### ISSUE THREAD

**Issue by intirules** [oushujun/LTR_retriever#17]
Hi, im trying to extract my results from the gff3 file to fasta and i get this 

$   bedtools getfasta -fi Muschr4.fsa -bed Muschr4.fsa.mod.pass.list.gff3 -fo ERVCom.fa 

WARNING. chromosome (seq0) was not found in the FASTA file. Skipping.
WARNING. chromosome (seq0) was not found in the FASTA file. Skipping.
WARNING. chromosome (seq0) was not found in the FASTA file. Skipping.
WARNING. chromosome (seq0) was not found in the FASTA file. Skipping.
WARNING. chromosome (seq0) was not found in the FASTA file. Skipping.
WARNING. chromosome (seq0) was not found in the FASTA file. Skipping.
WARNING. chromosome (seq0) was not found in the FASTA file. Skipping.
WARNING. chromosome (seq0) was not found in the FASTA file. Skipping.
WARNING. chromosome (seq0) was not found in the FASTA file. Skipping.

Its there another way to get the intact LTRs to fasta ?

**Comment by oushujun** [comment]
Hello,

Thanks for using LTR_retriever!

You can approach the goal using the following command lines:
`awk '{if ($1~/[0-9]+/) print $10"\t"$1}' Muschr4.fsa.mod.pass.list > Muschr4.fsa.mod.pass.list.extract`
`perl $path/LTR_retriever/bin/call_seq_by_list.pl Muschr4.fsa.mod.pass.list.extract -C Muschr4.fsa.mod > Muschr4.fsa.mod.pass.list.extract.fa`

Please let me know if you need further help.

Best,
Shujun

**Comment by intirules** [comment]
Thx for the rapid response
