### ISSUE TITLE
LTR_retriever produce different result in different data combine ways

### ISSUE THREAD

**Issue by LQ16** [oushujun/LTR_retriever#172]
Hi @oushujun,
I apologize for the inconvenience, but I'm facing an issue that I don't understand. When I run LTR_retriever using two different methods, I get different results.
In the first method, I use:

`LTR_retriever -genome $fa -noanno -inharvest 1.fa.mod.harvest.combine.scn -infinder 1.fa.mod.finder.combine.scn -threads 20`

In the second method, I combine the input files first:

`cat 1.fa.mod.harvest.combine.scn  1.fa.mod.finder.combine.scn > all.scn`
`LTR_retriever -genome $fa -noanno -inharvest all.scn -threads 20`

I noticed that the second method produces more LTR counts than the first method. Which result should I adopt?

**Comment by oushujun** [comment]
Hello,

Your LTR_FINDER result was produced by LTR_FINDER_parallel, whose default output is in LTRharvest format. So you will need to concatenate them together and provide them to LTR_retriever via -inharvest. Hope this clarifies your question.

Shujun
