### ISSUE TITLE
low LAI when using ltrharvest result as input

### ISSUE THREAD

**Issue by shiyi-pan** [oushujun/LTR_retriever#173]
Hi, shujun. LTR_retriever is an awesome tool and  I want to using it to evaluate my genome. 
But I found when I used ltrharvest result as input, the LAI is very low (3.66) ,  compared to using ltrfinder result as input, which was 10.54.

Here is my script sed ltrharvest result as input :

$LTRHARVEST suffixerator -db Chr01.fa -indexname Chr01.fa -tis -suf -lcp -des -ssp -sds -dna
$LTRHARVEST ltrharvest -index Chr01.fa -similar 90 -vic 10 -seed 20 -seqids yes -minlenltr 100 -maxlenltr 7000 -mintsd 4 -maxtsd 6 -motif TGCA -motifmis 1  > Chr01.harvest.scn

LTR_retriever -genome Chr01.fa -infinder ltr.finder.Chr01.scn -threads 4 -u 6.1e-9

I'm very confused, could you help me solve this problem,thank you very much.

**Comment by oushujun** [comment]
Hello, thank you for using LTR_retriever and LAI. It is required to use both LTRharvest and LTR_FINDER results as input to calculate LAI. LTRharvest alone is not sensitive enough.

Thanks,
Shujun
