### ISSUE TITLE
Is a writable `$genome` necessary?

### ISSUE THREAD

**Issue by GallVp** [oushujun/LTR_retriever#176]
Hi @oushujun 

Is a writable `$genome` necessary? This can cause problems in pipelines such as [Plant-Food-Research-Open/assemblyqc](https://github.com/Plant-Food-Research-Open/assemblyqc) where multiple tools are executed on the same genome. Changing the original file can result in misleading results by the other programs and reduce reproducibility. Thank you!

https://github.com/oushujun/LTR_retriever/blob/d4d72a2e3edd0033b9aeb4c54c718ff8e52911d7/LTR_retriever#L312

**Comment by GallVp** [comment]
I see, this is related to https://github.com/oushujun/LTR_retriever/pull/125

**Comment by GallVp** [comment]
This issue was resolved by RepeatMasker on Nov 2, 2022. Please see,

https://github.com/rmhubley/RepeatMasker/commit/3d83626710649d98222da7e0940a756138878fc0

https://github.com/rmhubley/RepeatMasker/blob/3d83626710649d98222da7e0940a756138878fc0/RepeatMasker#L741-L743

I guess it is safe now to remove the writable file check?

https://github.com/oushujun/LTR_retriever/blob/d4d72a2e3edd0033b9aeb4c54c718ff8e52911d7/LTR_retriever#L312

**Comment by oushujun** [comment]
Thank you for checking this out. I have removed this component.

Shujun
