### ISSUE TITLE
CP: cannot stat 'DM8.fa.retriever.scn.adj':No such file or directory

### ISSUE THREAD

**Issue by zxd-alt** [oushujun/LTR_retriever#177]
Hi shujun:
I got this problem and I changed genome but it still can't work.Please tell me how to deal this problem. THANK YOU VERY MUCH!                                    
                                                                                                                                                           BEST WISHES
                                                                                                                                                           KYLE

:$ ./LTR_retriever/LTR_retriever -genome DM8.fa -inharvest DM8.fa.harvest.scn -threads 12

############################
############################

Contributors: Shujun Ou, Ning Jiang

For LTR_retriever, please cite:

	Ou S and Jiang N (2018). LTR_retriever: A Highly Accurate and Sensitive Program for Identification of Long Terminal Repeat Retrotransposons. Plant Physiol. 176(2): 1410-1422.

For LAI, please cite:

	Ou S, Chen J, Jiang N (2018). Assessing genome assembly quality using the LTR Assembly Index (LAI). Nucleic Acids Res. 2018;46(21):e126.

Parameters: -genome DM8.fa -inharvest DM8.fa.harvest.scn -threads 12

2024年 07月 24日 星期三 09:51:11 CST	Dependency checking: All passed!
2024年 07月 24日 星期三 09:51:14 CST	LTR_retriever is starting from the Init step.
2024年 07月 24日 星期三 09:51:14 CST	Start to convert inputs...
				Total candidates: 14173
				Total uniq candidates: 14173

2024年 07月 24日 星期三 09:51:18 CST	Module 1: Start to clean up candidates...
				Sequences with 10 missing bp or 0.8 missing data rate will be discarded.
				Sequences containing tandem repeats will be discarded.

        Usage: perl cleanup.pl -f sample.fa [options] > sample.cln.fa 
	Options:
		-misschar	n	Define the letter representing unknown sequences; case insensitive; default: n
		-Nscreen	[0|1]	Enable (1) or disable (0) the -nc parameter; default: 1
		-nc		[int]	Ambuguous sequence len cutoff; discard the entire sequence if > this number; default: 0
		-nr		[0-1]	Ambuguous sequence percentage cutoff; discard the entire sequence if > this number; default: 1
		-minlen		[int]	Minimum sequence length filter after clean up; default: 100 (bp)
		-cleanN		[0|1]	Retain (0) or remove (1) the -misschar taget in output sequence; default: 0
		-trf		[0|1]	Enable (1) or disable (0) tandem repeat finder (trf); default: 1
		-trf_path	path	Path to the trf program
        
2024年 07月 24日 星期三 09:51:18 CST	0 clean candidates remained

cp: cannot stat 'DM8.fa.retriever.scn.adj': No such file or directory
2024年 07月 24日 星期三 09:51:18 CST	No LTR-RT was found in your data.

2024年 07月 24日 星期三 09:51:18 CST	All analyses were finished!

**Comment by oushujun** [comment]
Hello,

Sorry for the delay. Please check if you have the *retriever.scn.full and the *.ltrTE.fa files. You can generate the $index.ltrTE.fa file by: 
`perl $script_path/bin/call_seq_by_list.pl $index.retriever.scn.full -C $genome > $index.ltrTE.fa`

Then, please run:
`perl $script_path/bin/cleanup.pl -trf 1 -trf_path $trf -nc 10 -nr 0.8 -minlen 100 -minscore 1000 -f $genome.ltrTE.fa > $genome.ltrTE.stg1`

Let me know if you see any errors. 

Thanks!
Shujun

**Comment by oushujun** [comment]
@zxd-alt I found the bug, please update your code and try again. You may also want to add LTR_Finder results to increase the sensitivity.

Shujun

**Comment by zxd-alt** [comment]
> @zxd-alt I found the bug, please update your code and try again. You may also want to add LTR_Finder results to increase the sensitivity.
> 
> Shujun

HI,
Thanks for your reply. I've already finished this work. I use v2.95 can do it. 
BUT I met a question, when I exchange a genome that only 34m it showes that LAI is not applicable on the current genome assembly.  Could you give me a answer why is that? Maybe the size is too small only 34M or what?  When I use another genome which is 100m is ok,it can get the LAI.
                                                                              BEST WISHES
                                                                              ZXD
