### ISSUE TITLE
Uninitialized value error from get_range.pl

### ISSUE THREAD

**Issue by jackson-wells** [oushujun/LTR_retriever#18]
Running with harvest and finder inputs. The errors are produced when the program is executed with just harvest outputs, just finder outputs and when both are run together. The command utilized to run is as follows: `LTR_retriever -genome genome.fasta -inharvest harvScreen.out -infinder findScreen.out -threads 16`. The command is run using a batch scheduler as per infrastructure rules. 

The errors appear as follows:
Use of uninitialized value $seq_ID in exists at ./bin/get_range.pl line 120, <TBL> line 3.                                                                                          
Use of uninitialized value $seq_ID in exists at ./bin/get_range.pl line 120, <TBL> line 4.
Use of uninitialized value $seq_ID in exists at ./bin/get_range.pl line 120, <TBL> line 5.
Use of uninitialized value $seq_ID in exists at ./bin/get_range.pl line 120, <TBL> line 6.
.........
Use of uninitialized value $seq_ID in exists at ./bin/get_range.pl line 120, <TBL> line 135241.
Use of uninitialized value $seq_ID in exists at ./bin/get_range.pl line 120, <TBL> line 135242.
Use of uninitialized value $seq_ID in exists at ./bin/get_range.pl line 120, <TBL> line 135243.
Use of uninitialized value $seq_ID in exists at ./bin/get_range.pl line 120, <TBL> line 135244.
Warning: LOC list genome.fasta.retriever.scn.full is empty.
        Usage: perl cleanup.pl -f sample.fa [options] > sample.cln.fa
        Options:
                -misschar       n       Define the letter representing unknown sequences...
                -Nscreen        [0|1]   Enable (1) or disable (0) the -nc parameter; default: 1
                -nc             [int]   Ambuguous sequence len cutoff; discard the entire....
                -nr             [0-1]   Ambuguous sequence percentage cutoff; discard the entire sequence....
                -cleanN         [0|1]   Retain (0) or remove (1) the -misschar taget in output sequence
                -trf            [0|1]   Enable (1) or disable (0) tandem repeat finder (trf); default: 1
                -trf_path       path    Path to the trf program
cp: cannot stat ‘genome.fasta.retriever.scn.adj’: No such file or directory

I hope that this is sufficient information to assist with this error. All dependent software is up to date, to my knowledge. Also, LTR_retriever is configured to use CDHIT.

**Comment by oushujun** [comment]
Hello,

Sorry for the delay. Unfortunately, I could not determine the cause of this error. There is one possible cause: Your genome and `LTRharvest`/`LTR_finder` input files are not in the same version (usually due to the update of your assembly).

Other information that may help to pinpoint the error, could you provide the program status information before and after this error?

Thanks,
Shujun

**Comment by jackson-wells** [comment]
Thank you for the response,

The genome file utilized to generate harvest and finder outputs has not changed since said outputs were created. The LTR_finder version used was 1.0.7. The iteration of LTRharvest used was contained in GenomeTools 1.5.9.

In the previous post I supplied only the error output in its entirety, sourced from the batch scheduler's output error file. The following information is contained in a complementary batch scheduling output file from the same job:  

##########################
### LTR_retriever v1.8.0 ###
##########################

Contributors: Shujun Ou, Ning Jiang

Please cite: Ou S, Jiang N: LTR_retriever: a highly accurate and sensitive program for identification of long terminal repeat retrotransposons. Plant Physiology 2018, 176:1410-1422
Parameters: -genome genome.fasta -inharvest harvScreen.out -infinder findScreen.out -threads 16


Fri Aug 10 12:43:59 PDT 2018    Dependency checking: All passed!
Fri Aug 10 12:45:31 PDT 2018    Start to convert inputs...
                                Total candidates: 135242
                                Total uniq candidates: 0

Fri Aug 10 12:46:36 PDT 2018    Module 1: Start to clean up candidates...
                                Sequences with 10 missing bp or 0.8 missing data rate will be discarded.
                                Sequences containing tandem repeats will be discarded.
printed to screen and 
Fri Aug 10 12:46:36 PDT 2018    0 clean candidates remained

Fri Aug 10 12:46:36 PDT 2018    No LTR-RT was found in your data.

Fri Aug 10 12:46:36 PDT 2018    All analyses were finished!


This is the extent of the information pertaining to the error. Again, I hope this will provide sufficient information to get to the bottom of whats going wrong. 

Thank you for any help/insight,
Jackson

**Comment by jackson-wells** [comment]
Accidentally closed the issue, apologies.

**Comment by jackson-wells** [comment]
Hello Shujun,

You were correct about the input files. It would seem I made a very silly mistake with my LTRharvest output file. I was inputting a file to LTR_retriever that was in FASTA format, instead of the required coordinate format. LTR_retriever is now running happily and is expected to provide an actual output this time around. Thank you for all of your help and speedy replies. 

Cheers,

Jackson Wells
