### ISSUE TITLE
LTR_retriever for ERROR: No candidate is found in the file(s) you specified.

### ISSUE THREAD

**Issue by Jasminefyh** [oushujun/LTR_retriever#181]
Hi,
   I used LTR_retriever for identifying LTR and calculate LAI of ferns, which were confirmed have high rate of LTRs. I installed both LTR_retriever v3.0.1 and v2.9.4. And here is my commond:
`gt suffixerator -db ./Non-seed_plants_database/Ferns_Azolla_filiculoides/1_Azolla_filiculoides.fa -indexname index_azfi/azfi -tis -suf -lcp -des -ssp -sds -dna
gt ltrharvest -index ./index_azfi/azfi -minlenltr 100 -maxlenltr 7000 -mintsd 4 -maxtsd 20 -motif TGCA -motifmis 1 -similar 85 -vic 10 -seed 20 -seqids yes >genome.azfi.harvest.scan
LTR_FINDER_parallel -seq ./Non-seed_plants_database/Ferns_Azolla_filiculoides/1_Azolla_filiculoides.fa -threads 24 -harvest_out -size 5000000 -time 1500 -w 2 -C -D 15000 -d 1000 -L 7000 -l 100 -p 20 -M 0.85
LTR_retriever -genome 1_Azolla_filiculoides.fa -inharvest genome.azfi.harvest.scan -infinder 1_Azolla_filiculoides.fa.finder.combine.scn -threads 50 &>afzi.lai.log
`
However, the output file "1_Azolla_filiculoides.fa.nmtf.pass.list" is empty with " ERROR: No candidate is found in the file(s) you specified." in .log file. 

I have also tested Arabidopsis genome as a control, but also get the same results.  I have no idea how to handle this problem. 

Sincerely

**Comment by Jasminefyh** [comment]
I've also tested pipeline below

`cat genome.azfi.harvest.scan 1_Azolla_filiculoides.fa.finder.combine.scn >afzi.fa.rawLTR.scn
LTR_retriever -genome ./1_Azolla_filiculoides.fa -inharvest ./afzi.fa.rawLTR.scn -threads 50 &>afzi.ltr-retriever.log`

However, it also failed with the following error:
![ltr_error](https://github.com/user-attachments/assets/936e1daa-1489-4369-8f86-1612acc5a9b8)

Looking forward for your reply and thank you very much.

**Comment by oushujun** [comment]
Duplicated issue. Please search other issues.

Shujun

**Comment by Jasminefyh** [comment]
Dear Shujun,

        Thank you for the quick reply. I have read the similar issue contents of https://github.com/oushujun/LTR_retriever/issues/135 and https://github.com/oushujun/LTR_retriever/issues/139. I have updated the software LTR_retriever to v2.9.8 and v3.0.1, however, I still got the same log error:

`
##########################
### LTR_retriever v2.9.8 ###
##########################

Contributors: Shujun Ou, Ning Jiang

For LTR_retriever, please cite:

	Ou S and Jiang N (2018). LTR_retriever: A Highly Accurate and Sensitive Program for Identification of Long Terminal Repeat Retrotransposons. Plant Physiol. 176(2): 1410-1422.

For LAI, please cite:

	Ou S, Chen J, Jiang N (2018). Assessing genome assembly quality using the LTR Assembly Index (LAI). Nucleic Acids Res. 2018;46(21):e126.

Parameters: -genome aca_3M.fa -inharvest aca.fa.rawLTR.scn -threads 5


2024年 10月 28日 星期一 09:21:50 CST	Dependency checking: All passed!
2024年 10月 28日 星期一 09:21:58 CST	LTR_retriever is starting from the Init step.
2024年 10月 28日 星期一 09:21:58 CST	The longest sequence ID in the genome contains 14 characters, which is longer than the limit (13)
				Trying to reformat seq IDs...
				Attempt 1...
2024年 10月 28日 星期一 09:21:58 CST	Seq ID conversion successful!

2024年 10月 28日 星期一 09:21:58 CST	Start to convert inputs...
				Total candidates: 124
				Total uniq candidates: 124

2024年 10月 28日 星期一 09:21:58 CST	Module 1: Start to clean up candidates...
				Sequences with 10 missing bp or 0.8 missing data rate will be discarded.
				Sequences containing tandem repeats will be discarded.


        Usage: perl cleanup.pl -f sample.fa [options] > sample.cln.fa 
	Options:
		-misschar	n	Define the letter representing unknown sequences; case insensitive; default: n
		-Nscreen	[0|1]	Enable (1) or disable (0) the -nc parameter; default: 1
		-nc		[int]	Ambuguous sequence len cutoff; discard the entire sequence if > this number; default: 0
		-nr		[0-1]	Ambuguous sequence percentage cutoff; discard the entire sequence if > this number; default: 1
		-minlen		[int]	Minimum sequence length filter after clean up; default: 100 (bp)
		-cleanN		[0|1]	Retain (0) or remove (1) the -misschar taget in output sequence; default: 0
		-trf		[0|1]	Enable (1) or disable (0) tandem repeat finder (trf); default: 1
		-trf_path	path	Path to the trf program
        
2024年 10月 28日 星期一 09:21:58 CST	0 clean candidates remained

cp: 无法获取"aca_3M.fa.mod.retriever.scn.adj" 的文件状态(stat): 没有那个文件或目录
2024年 10月 28日 星期一 09:21:58 CST	No LTR-RT was found in your data.

2024年 10月 28日 星期一 09:21:59 CST	All analyses were finished!
`

[aca_3M.retriever.log](https://github.com/user-attachments/files/17536237/aca_3M.retriever.log)

As my RepeatMasker and RepeatModelar was installed by myself instead of anaconda, is it possible that the dependences for the direction of RepeatMasker and RepeatModelar should be configured?

Thanks for your help!

Jasmine

**Comment by Jasminefyh** [comment]
Dear Shujun,

I resolved this issue by commenting out RepeatMasker and RepeatModeler in the environment variables and updating LTR_retriever to version 3.0.1. The newly installed LTR_retriever depends on RepeatMasker installed via conda. Now, all the LTR programs are running smoothly.

Thank you very much~

**Comment by oushujun** [comment]
Awesome! I am glad you solved the issue. You may also want to convert your sequence IDs to a tidy short form before running any downstream analysis.

Best,
Shujun

**Comment by likai888** [comment]
ERROR: No candidate is found in the file(s) you specified.
same error as this issue. 
LTR_retriever -genome genome.fa -infinder genome.fa.finder.combine.scn -threads 32 

is there any option i missed?

best regard,
Kai

**Comment by likai888** [comment]
Thank you so much for your  prompt reply.
I double check the .scn file which is not empty and has 404 available records.
$ wc -l genome.fa.finder.combine.scn
405

Best regard,
Kai
