### ISSUE TITLE
script to generate the Figure 4 in the LAI paper

### ISSUE THREAD

**Issue by xinshuaiqi** [oushujun/LTR_retriever#23]
Hi Shujun, 
Which package or library did you used to generate the plot on Figure 4 in the LAI paper? 
Do you mind to share an example of your script? Thank you.

**Comment by oushujun** [comment]
The method for Manhattan plots in Figure 4 was provided in the paper.
>Manhattan plots were generated using the qqman package in R (https://github.com/stephenturner/qqman).

Please refer to @stephenturner for paticular questions for this method. Thanks.
