### ISSUE TITLE
Errors in running LTR.identifier.pl

### ISSUE THREAD

**Issue by caixu0518** [oushujun/LTR_retriever#26]
Hi Shujun,

I encountered the following problem when running LTR_retriever. I don't know if these errors affect the results, or how I should fix them.

Tue Nov 13 22:48:20 CST 2018    Modules 2-5: Start to analyze the structure of candidates...
                                The terminal motif, TSD, boundary, orientation, age, and superfamily will be identified in this step.

substr outside of string at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin### /LTR.identifier.pl line 317.
Use of uninitialized value $seed in index at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 321.
substr outside of string at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 317.
Use of uninitialized value $seed in index at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 321.
Use of uninitialized value $probTSD in uc at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 325.
substr outside of string at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 317.
Use of uninitialized value $seed in index at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 321.
Use of uninitialized value $probTSD in uc at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 325.
Use of uninitialized value $TSDlen in numeric le (<=) at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 334.
Use of uninitialized value $probTSD in uc at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 334.
Use of uninitialized value $probTSD in index at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 358.
Use of uninitialized value $TSDlen in addition (+) at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 358.
Use of uninitialized value $probTSD in index at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 359.
Use of uninitialized value $TSDlen in numeric lt (<) at /disk02/caix/src/LTR_retriever/LTR_retriever-1.9/bin/LTR.identifier.pl line 360.
Wed Nov 14 00:25:57 CST 2018    Intact LTR-RT found: 5490

Wed Nov 14 00:35:14 CST 2018    Module 6: Start to analyze truncated LTR-RTs...
                                Truncated LTR-RTs without the intact version will be retained in the LTR-RT library.
                                Use -notrunc if you don't want to keep them.

best,
Xu Cai

**Comment by oushujun** [comment]
Hi Xu Cai,

If you only received a couple of such errors and the program produces intact LTR-RTs, as indicated in your standard output, you should be fine. This is likely the case that a small number of candidates are located at the boundary of contigs, such that no flanking sequence is available for the extraction. Missing these candidates will not produce significant bias. I will further work on a solution for this.

Thanks,
Shujun

**Comment by caixu0518** [comment]
Many thanks.
