### ISSUE TITLE
Questions about *.pass.list

### ISSUE THREAD

**Issue by rapaJiahe** [oushujun/LTR_retriever#29]
Hi Shujun,

From the log file, i know *.pass.list contain the whole genome LTR-RTs (redundant). I found some LTR-RT have the same coordinate with different TSD.
**C01:2584769..2588663**    pass    motif:TGCA      **TSD:ATTAC**       2584764..2584768        2588664..2588668        IN:2585668..2587763     0.9911  ?       unknown NA      344355
**C01:2584769..2588663**    pass    motif:TGCA      **TSD:GTAAT**       2584764..2584768        2588664..2588668        IN:2585668..2587763     0.9911  -       unknown NA      344355

I don't know why this happens. Are both results reliable LTR-RTs?

Best,
Jiahe

**Comment by oushujun** [comment]
#28

**Comment by oushujun** [comment]
Hi Jiahe,

This is the same element which is likely a genuine LTR element. One of the TSDs was not converted to the complementary form due to the ambiguity of direction. I have fixed this minor bug in the later updated version. Thanks for using LTR_retriever!

Cheers,
Shujun
