### ISSUE TITLE
Best way to get LAI value per contig/scaffold

### ISSUE THREAD

**Issue by shkao** [oushujun/LTR_retriever#30]
Hi Shujun,

What would be the best way to get the LAI values for each contig/scaffold that you would recommend?
Thanks!

**Comment by oushujun** [comment]
Hi Allen,

You may run with the whole genome and set a ridiculously large window size
so that each contig is in only one window.

Thanks,
Shujun

**Comment by shkao** [comment]
Thank you, Shujun. That was quick!
