### ISSUE TITLE
Use of uninitialized value $ac/$bd

### ISSUE THREAD

**Issue by yuanhelianyi** [oushujun/LTR_retriever#33]
I am getting the following error while running v2.0. I don't know what caused it. Please help me.
Error: Argument "num_threads". Illegal value, expected (>=1 and =<32):  `40'
Use of uninitialized value $bd in substitution (s///) at /data2/zhaoJing/bin/LTR_retriever-2.0/bin/LTR.identifier.pl line 301.
Use of uninitialized value $ac in substitution (s///) at /data2/zhaoJing/bin/LTR_retriever-2.0/bin/LTR.identifier.pl line 300.
Use of uninitialized value $ac in pattern match (m//) at /data2/zhaoJing/bin/LTR_retriever-2.0/bin/LTR.identifier.pl line 303.
Use of uninitialized value $bd in pattern match (m//) at /data2/zhaoJing/bin/LTR_retriever-2.0/bin/LTR.identifier.pl line 303.

**Comment by oushujun** [comment]
It seems that only one LTR candidate is affected by this issue, so you may just ignore it by now. I will push a bug fix in the next update.

**Comment by yuanhelianyi** [comment]
Thank you very much. I want to confirm wether the  one LTR candidate indicate the retrotransposons with only one LTR, ie.,the solo-LTR  or not. I found many lines of the error in my out file.

**Comment by oushujun** [comment]
Probably not. LTR_retriever is not designed to identify solo-LTRs. All input candidates should have a pair of long terminal-repeat.
