### ISSUE TITLE
Can you send me find_ltr_DAWGPAWS.pl you have used?

### ISSUE THREAD

**Issue by wangzhennan14** [oushujun/LTR_retriever#35]
Hi,
    Can you send me the MGEScan_LTR packages you have used in this paper? I have downloaded some packages, but they did not work. Could you send me the (a modified version obtained from DAWGPAWS) to wangzhennan@ioz.ac.cn? Thank you very much!

                                                                          Wangzhennan

**Comment by oushujun** [comment]
Dear Wangzhennan,

You may download MGEScan_LTR and the PAWGPAWS version from here: http://darwin.informatics.indiana.edu/evolution/data/sw/

Previously, I just modified file paths to dependent programs in find_ltr_DAWGPAWS.pl. However, the search engine of this package is too old to run in my new HPC environment, and I could not make it run anymore. You may want to try it yourself: 
`cd ./ltr/MER`
`./ltr`
If it gives you help info, then it still works in your system. Then you may want to read the README and modify dependencies in find_ltr_DAWGPAWS.pl. What you want to get from this program is the output format like LTRharvest, which require some coding skills to transform the original output, then feed the output to LTR_retriever by:
`./LTR_retriever -inharvest MGEScan_LTR.output`

I will close this thread for now. You may reopen it or comment below if you have further questions.

Good luck! 

Best,
Shujun
