### ISSUE TITLE
No such file or directory output_by_list.pl line 35

### ISSUE THREAD

**Issue by crisvives** [oushujun/LTR_retriever#36]
Hi Shujun,
I am getting the following error:
ERROR: No such file or directory at /usr/local/apps/eb/LTR_retriever/1.6-foss-2016b/bin/output_by_list.pl line 35. 

The simplified command that I am using is this one: 
LTR_retriever -genome $genome_file -inharvest $genome.ltrharvest.scn -infinder $genome.ltrfinder.scn -nonTGCA $genome.ltrharvest.nonTGCA.scn > $genome_file.LTR_retriever.out

It seems that is missing $genome_file.nmtf.ltrTE, but while LTR-Retriever is running, the following files with names having "$genome_file.nmtf.ltrTE*" are generated:

$genome_file.nmtf.ltrTE.LTR Sa_scaffold.fa.nmtf.ltrTE.LTR.masked $genome_file.nmtf.ltrTE.LTR.ori.out Sa_scaffold.fa.nmtf.ltrTE.LTR.tbl $genome_file.nmtf.ltrTE.fa.cleanup Sa_scaffold.fa.nmtf.ltrTE.stg1
$genome_file.nmtf.ltrTE.LTR.cat Sa_scaffold.fa.nmtf.ltrTE.LTR.masked.cleanup $genome_file.nmtf.ltrTE.LTR.out Sa_scaffold.fa.nmtf.ltrTE.fa Sa_scaffold.fa.nmtf.ltrTE.pass.list

Thank you for your help!
Cristina

**Comment by oushujun** [comment]
Hi Cristina,

Thanks for your error message. It seems that the expected files are put in an unexpected folder.
you may move `LTR_retriever/1.6-foss-2016b/bin` to `LTR_retriever/` and should solve the problem.

If not, just download a fresh version of LTR_retriever and copy over the `LTR_retriever/path` file, and you should be good.

Please let me know if you need further help.

Best,
Shujun

**Comment by crisvives** [comment]
I could solve the problem by moving files in to LTR_retriever/ folder.
Thanks for your help, Shujun!
