### ISSUE TITLE
LTR superfamily summary and distribution output

### ISSUE THREAD

**Issue by bioteksampath** [oushujun/LTR_retriever#37]
Hi,

My LTR-retriever run does give all the outputs except three of the following.
I just wonder how to get these as well, do i need to specify in my run?

The output of LTR_retriever includes:
LTR family summary (.out.fam.size.list)
LTR superfamily summary (.out.superfam.size.list)
LTR distribution on each chromosome (.out.LTR.distribution.txt)

cmd used:
/LTR_retriever -genome Bnigra_ref2_genome.fasta -inharvest Bnigra_ref2_genome.harvest.nonTGCA.scn -infinder Bnigra_ref2_genome.LTRfinder.scn -blastclust -L .9 -b T -S 80 -threads 10

Thanks a lot!
Sam

**Comment by oushujun** [comment]
Hi Sam,

The parameter format you provided to `blastclust` needed to be adjusted. You may try:

`/LTR_retriever -genome Bnigra_ref2_genome.fasta -inharvest Bnigra_ref2_genome.harvest.nonTGCA.scn -infinder Bnigra_ref2_genome.LTRfinder.scn -blastclust -threads 10`

or if you want to customize parameters for `blastclust` other than the default, you may do:

`/LTR_retriever -genome Bnigra_ref2_genome.fasta -inharvest Bnigra_ref2_genome.harvest.nonTGCA.scn -infinder Bnigra_ref2_genome.LTRfinder.scn -blastclust [-L .9 -b T -S 80] -threads 10`

If the program runs correctly, it should produce the three files you are looking for. Could you paste here the STDOUT infomation? There may be some errors preventing it from generating these files. If you think it runs correctly, you may run these scripts alone:

`perl /LTR_retriever/bin/fam_coverage.pl $genome.LTRlib.fa $genome.out $genome_size > $genome.out.fam.size.list`

`perl /LTR_retriever/bin/fam_summary.pl $genome.out.fam.size.list $genome_size > $genome.out.superfam.size.list`

`perl /LTR_retriever/bin/LTR_sum.pl -genome $genome -all $genome.out > $genome.out.LTR.distribution.txt`

Please let me know if you need further help.

Best,
Shujun

**Comment by oushujun** [comment]
You may reopen this issue if your problem is not solved. Thanks! Shujun

**Comment by bioteksampath** [comment]
yes, it worked after updating to the new version!
Thanks oushujun.
