### ISSUE TITLE
*.pass.list and *.pass.list.gff3 have different row number

### ISSUE THREAD

**Issue by SCQUchenyang** [oushujun/LTR_retriever#39]

**Comment by SCQUchenyang** [comment]
Hi，
I have run LTR_retriever with the output from LTR-finder and LTRharvest. I have got the result.But  I find the *.pass.list.gff3  have 38264 rows，but *.pass.list only has 5236 rows. I want to get insert time of all intact LTR-RTs. The *.pass.list only show some of them?
And, I have another question.Can LTR_retriever class the LTR-RT(Copia and Gyspy) into smaller family?such as TAT or Tork？
Thanks for your time and help.
Chenyang

**Comment by oushujun** [comment]
Hello Chenyang,

Thanks for using LTR_retriever. Your numbers make sense to me. If you take a closer look at the *.pass.list.gff3 file, you may find each intact LTR element is described by 7 lines. If you are looking for insertion times of each intact element, you may use the *.pass.list file, in which the last column is the estimated insertion time based on the JC69 model.

The current version of LTR_retriever only classifies intact elements into Copia/Gypsy. For further classification, you may want to use HMMER and related HMM profiles.

Please let me know if you have further questions.

Thanks,
Shujun
