### ISSUE TITLE
call_seq_by_list.pl uninitialized $chr_pre ?   It will cause nagative start or end. 

### ISSUE THREAD

**Issue by YuntaoTan** [oushujun/LTR_retriever#40]
Hi, 
  oushujun,
  I use the Ltr_retriver find LTR based on LTR_finder and LTR haverst result. but I got the error:
`call_seq_by_list.pl uninitialized $chr_pre`
So  I find the 84 line. 
Floowing I found,
`my $chr_pre=$1 if (split /\s+/, $list[0])[1]=~/(.*):-?[0-9]+\.\.[0-9]+$/;`
I anaysis the code , it may be cased by too short scaffold, when the program extend the sequence forward or backward. It will occur nagative start or end. 
I try to change the code to 
`my $chr_pre=$1 if (split /\s+/, $list[0])[1]=~/(.*):-?[0-9]+\.\.-?[0-9]+$/;`
make it match the nagtive end.  but failed, other Error I encountered.
Can you help me ?
How can i fix this Error?

**Comment by oushujun** [comment]
Hello @YuntaoTan ,

Thank you for using LTR_retriever. You may try to replace line 84 with:
`my $chr_pre=$1 if (split /\s+/, $list[0])[1]=~/(.*):[\-0-9]+\.\.[\-0-9]+$/;`
Let me know if this works or not.

If you have negative coordinates in the list, the bug may be inherited in former steps. Which step are you having this error? Can you paste the LTR_retriever status output here? A sample of the list file will be also helpful to track down the bug. Thanks!

Best,
Shujun

**Comment by oushujun** [comment]
Close due to no response. Please reopen this issue if you have further questions.
