### ISSUE TITLE
Length ratio between LTR and the internal region (-max_ratio)

### ISSUE THREAD

**Issue by anandksrao** [oushujun/LTR_retriever#42]
Greetings!

I have my LTRharvest and LTR_finder results ready to feed to LTR_retriever. I have one observation and a few questions based on it, before I use your software. Please read on:

**Observation** [from your manuscript]:
In your LTR_retriever [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5813529/), it 
says "Empirically, more than 95% of LTR-RTs range from 1 to 15 kb"

In your user [manual](https://github.com/oushujun/LTR_retriever/blob/master/Manual.pdf), here on Github, default parameters are:
-minlen [INT] =  specify the minimum length (bp) of the LTR region (100)
-max_ratio [FLOAT] = specify the maximum length ratio of the internal region over the LTR region (default 50)

**Questions**:

**1.** Would it not be better to use --max_ratio = 15KB / 100bp = 150?

**2.** Do you think / know if there will be any drawbacks in using  --max_ratio 150, rather than your default  --max_ratio 50?

**3.** In the remaining 5% of LTR-RTs, how much shorter and longer can they be, based on your empirical determination?

**4.** Can LTR internal length be specified independent of flanking LTR sequence length? I mean, is there a --max-length parameter than can override --max_ratio if there are LTR-RTs outliers, in terms of internal sequence length?
 
Thanks, in advance, Shujun!

**Comment by oushujun** [comment]
Hi Anand,

These are very careful thoughts. I believe we tried --max_ratio = 15KB / 100bp = 150 but it ended up too inclusive, which will result in very short LTRs flanking very long internal regions. Such a case is likely a nested insertion, either nested with LTR elements or other TEs, which will decrease the accuracy of the library. You may try it on your genome, and see if you find such extreme cases.

Other than the general length of LTR elements, we also noticed some extremely short or long elements during our curation. As short as 70bp for the LTR region, and as long as 20-30kb for the whole element, these elements are very difficult to discriminate between false positives based on the current algorithm, so we narrowed down the range for a more confident inference. 95% is just a rough estimate based on our library comparison with the manually curated library.

So far we don't see the necessity of controlling the internal length independently. We may implement it in the future if we find such a need. Please let me know if you have further questions.

Best,
Shujun
