### ISSUE TITLE
Ltr insertion time

### ISSUE THREAD

**Issue by mqding0564** [oushujun/LTR_retriever#44]
hi，this is a very good software, I noticed this software gives the insertion time, could you please explain what kind of algorithm you use to get the insertion time? And the unit of the insertion time column? Is it the year or not.

**Comment by oushujun** [comment]
Hello,

Thanks for using LTR_retriever. Insertion time of each intact LTR element
is given in the .pass.list file. By default the mutation rate is 1.3e-8 per
bp per year (rice), so the unit is calendar year. You may specify a
different rate by providing -u/-miu. For the calculation algorithm please
read our Plant Physiology paper.

Best,
Shujun

**Comment by U201412486** [comment]
Hi,
  I have the LTR gff3 file.
How should I do If I just want to use LTR_retriever to compute the insertion time of the LTR ?
Thanks,
sun,

**Comment by oushujun** [comment]
Hi @U201412486,

Please see the information above. If you can find `divergence` or `identity` in the gff3 file, then you can calculate the insertion time by hand or excel with T = K/2µ, K is the divergence of the LTR = 1 - identity.

Best,
Shujun

**Comment by U201412486** [comment]
@oushujun Thank you for your answer.
    I need to caculate sequence identity between the 5' and 3' direct repeats of an LTR candidate firstly.I do not know how to extract  5' and 3' direct repeats sequnce of  an LTR.Can you give me advice?
many thanks,
sun

**Comment by oushujun** [comment]
The easiest way is to look it up in the LTR_retriever output file such as
*gff3 or *.pass.list. You may recalculate it by yourself. To extract a
sequence, one solution is to use the LTR_retriever/bin/call_seq_by_list.pl
script.

SHujun

**Comment by U201412486** [comment]
The LTR_retriever/bin/call_seq_by_list.pl can be used to extract sequences accroding to the coordinate.So how can I get the coordinate of  the 5' and 3' direct repeats of an LTR? The thing is that I  do not know how to idenified the coordinates of the 5' and 3' direct repeats of an LTR.

Best,
sun

**Comment by oushujun** [comment]
Please find this info in *gff3 or *.pass.list.

**Comment by U201412486** [comment]
Thank you so much.
Can you tell me the process of extracting the 5' and 3' direct repeats of an LTR such as any script ?

**Comment by oushujun** [comment]
As I have mentioned above,  you can use the info in the pass.list or gff3
file for the LTR coordinate and the call_seq_by_list.pl script to call
these regions.

Shujun

**Comment by Prabhu89-code** [comment]
Dear Dr. Ou Shu Jun,
         Can I use the unit of "Insertion_Time" as Milion Years Ago (MYA) by dividing the result by 10,00,000? 
Fo eg., 595557 as 0.595 MYA ?

Thanking you!
Regards,
Prabhu, S

**Comment by oushujun** [comment]
@Prabhu89-code Yes you can. You can even reestimte the time with the mutation rate of your species (µ, per bp per year) using the identity with T = (1 - identity%) / 2µ. 

Best,
Shujun

**Comment by Prabhu89-code** [comment]
Thank you for your reply Dr. Shu Jun.
I have never done mutation rate and insertion time calculation. I am working in Peach. I will try to collect information from literatures and reestimate with the formula you mentioned.

Thanking you!

Regards,
Prabhu, S

**Comment by Prabhu89-code** [comment]
Dear Dr. Shu Jun,
        What about the identity percentage of 1.  How do we estimate those LTR's insertion time.

Thanking you !

Regards,
Prabhu, S

**Comment by oushujun** [comment]
That's not 1% but 100%. Age of 0. -Shujun

**Comment by Prabhu89-code** [comment]
So, the age of '0' is correct ? What it means in terms of insertion time.

-Prabhu

**Comment by oushujun** [comment]
That means no differentiation between the left and right LTR. The insertion
could happen right before the sampling of the tissue or a couple hundred
years ago. But there is no differentiation of the LTR pair so the age is
estimated 0.  -Shujun

**Comment by Prabhu89-code** [comment]
Dear Dr. Shu Jun,
         Thank you very much for your clarification. Now I understood it completely. Your answers are so helpful in understanding about LTR.

Thanking you!

Regards,
Prabhu, S

**Comment by oushujun** [comment]
I am glad it helps. -Shujun

**Comment by wensulin93** [comment]
Hello shujun, @oushujun 


I noticed that some identities in the LTR_Retriever result file are less than 0.01, and then the insertion_time column shows up as "NA". How do you explain this?
![image](https://user-images.githubusercontent.com/63379795/177518156-c3adb7e6-a2ea-47ef-8583-26a943d20e8c.png)

**Comment by wensulin93** [comment]
hello， @oushujun 



Only part of it. There are dozens of them out of thousands, as shown in the picture. And only below 0.01 (jump directly from 0.9 to 0.01). The LTR_Retriever version I'm using is 2.9.0. Because I'm involved in calculating the insertion time, but if you start with &lt; A value of 0.01 for insertion time would show significant outliers over billions of years (second picture), which is clearly not possible. Then I noticed that in gCA_019656295.1_rRI_R1.1_genom.fna.mod.pass, the default insertion time value (Identity &lt; 0.01) is NA, so I excluded these identity &lt in my subsequent continuation; At 0.01, the distribution of insertion time seemed normal. It also seems that TEsorter can rule out these outliers.

 

![image](https://user-images.githubusercontent.com/63379795/177668144-f785bad6-af04-4f10-8686-1967352990e6.png)


![image](https://user-images.githubusercontent.com/63379795/177670682-2bdfd9a7-6903-4e2b-9014-7091281c7d4a.png)

**Comment by oushujun** [comment]
Hi,

Can you send me the .defalse file to further check on these candidates? Thank you.

Shujun
shujun.ou.1@gmail.com

**Comment by wensulin93** [comment]
> Hi,
> 
> Can you send me the .defalse file to further check on these candidates? Thank you.
> 
> Shujun [shujun.ou.1@gmail.com](mailto:shujun.ou.1@gmail.com)

Has been sent.

**Comment by Wenwen012345** [comment]
> > Hi,
> > Can you send me the .defalse file to further check on these candidates? Thank you.
> > Shujun [shujun.ou.1@gmail.com](mailto:shujun.ou.1@gmail.com)
> 
> Hello, @oushujun
> 
> Upon inspection, it looks like that the reason is LTR_Retriever running on the PC（Core i5-9400F，6 CORES, 16GB RAM）. Initially I was running on a PC and got a lot of "<0.01 identity", as shown below. ![下载 (2)](https://user-images.githubusercontent.com/63379795/178025886-123d69e2-c799-4e24-a8a1-f817a89167b3.png)
> 
> But once I ran it on the server (120G RAM, 40 CORES), there were almost no items less than 0.01 identity, as shown below。
> 
> ![下载 (3)](https://user-images.githubusercontent.com/63379795/178026133-df20dd54-509f-4528-9e8e-01b3e00888fa.png)
> 
> Is LTR_Retriever automatically skipping hard-to-handle projects due to computer capabilities? Please refer to and add appropriate instructions in the main page. Due to network reasons and time constraints, LTR_Retriever cannot be run for PC for further testing. I will further test in my spare time and inform you of the results!
> 
> By the way, the BLASTN version on the server is 2.5.0+; On the PC, it's 2.12.0+.
> 
> Thank you very much!



> > Hi,
> > Can you send me the .defalse file to further check on these candidates? Thank you.
> > Shujun [shujun.ou.1@gmail.com](mailto:shujun.ou.1@gmail.com)
> 
> Hello, @oushujun
> 
> Upon inspection, it looks like that the reason is LTR_Retriever running on the PC（Core i5-9400F，6 CORES, 16GB RAM）. Initially I was running on a PC and got a lot of "<0.01 identity", as shown below. ![下载 (2)](https://user-images.githubusercontent.com/63379795/178025886-123d69e2-c799-4e24-a8a1-f817a89167b3.png)
> 
> But once I ran it on the server (120G RAM, 40 CORES), there were almost no items less than 0.01 identity, as shown below。
> 
> ![下载 (3)](https://user-images.githubusercontent.com/63379795/178026133-df20dd54-509f-4528-9e8e-01b3e00888fa.png)
> 
> Is LTR_Retriever automatically skipping hard-to-handle projects due to computer capabilities? Please refer to and add appropriate instructions in the main page. Due to network reasons and time constraints, LTR_Retriever cannot be run for PC for further testing. I will further test in my spare time and inform you of the results!
> 
> By the way, the BLASTN version on the server is 2.5.0+; On the PC, it's 2.12.0+.
> 
> Thank you very much!

This was a previous question, but I recently tried running LTR-Retriever in my PC. I use a virtual machine, linux system, ubuntu. Results showed no abnormalities. different from the previous ones. I deliberately put the files required for running on the hard disk in the virtual machine to run (it was run on a shared hard disk before.). The results show that there are only a few LTRs (3) with Identity<0.01, indicating that the software runs without problems. Maybe it was because the running file was placed in the shared folder before? In short, the LTR_Retriever running on the PC is displayed normally. Although some of the analysis I usually do in the biographies is mainly done on the server.

**Comment by tytrhr** [comment]
Hello, @oushujun
If the -u parameter is not added, is the default evolutionary rate calculated for rice 1.3e-8?

**Comment by Jwindler** [comment]
> Hello, [@oushujun](https://github.com/oushujun) If the -u parameter is not added, is the default evolutionary rate calculated for rice 1.3e-8?

yes
