### ISSUE TITLE
Problem with The RMblast engine dependency problem

### ISSUE THREAD

**Issue by moontree1985** [oushujun/LTR_retriever#45]
Hi, Shujun,

I am facing the same problem with dependency of RMblast engine. I tried to follow Nancy's suggestions #43 . I don't have Taxononmy::new() error but successfully got the following files:

dummy060817.fa.926962 dummy060817.fa.926962.masked dummy060817.fa.926962.nin dummy060817.fa.926962.ori.out dummy060817.fa.926962.tbl
dummy060817.fa.926962.cat dummy060817.fa.926962.nhr dummy060817.fa.926962.nsq dummy060817.fa.926962.out

However, when I run ltrretriever 2.5 and ltrretriever 2.1 , I still got error:
Dependency checking: The RMblast engine is not installed in RepeatMasker!

I don't have this error when I use ltrretriever 1.6 and 20170514. 

Best,

Ying

**Comment by oushujun** [comment]
Hi Ying,

Sorry that RepeatMasker is not working for you. I added more detailed guidelines in #43, hopefully you can follow them through and fix the issue. Please let me know if you encounter new issues.

Best,
Shujun

**Comment by moontree1985** [comment]
Hi, Shujun,

I followed your suggestions to try to fix the problem. However, the dependency checking is still failed. Then I tried to use version 1.6 and it works. I am wondering version 2.5 may need to compare with 1.6 to fix this dependency problem.

Thanks,

Ying

**Comment by oushujun** [comment]
Hi Ying,

For dependency checking, the difference between v1.6 and v2.5 is the use of a random number generator to avoid interference between LTR_retriever runs in the same directory. From your initial post, the random number generator seems working in your system, so there should be no difference.

I tried a new clone of v2.5 and followed the fix instruction in #43, didn't have a failure for the RepeatMasker dependency. You may start fresh and try again. If you already did, can you paste the output of running this command? 

`RepeatMasker -e ncbi -q -pa 1 -no_is -norna -nolow dummy060817.fa* -lib dummy060817.fa*`

Can you please let me know your system platform?

Best,
Shujun

**Comment by moontree1985** [comment]
Hi, Shujun,

I run the following script:
module load ltrretriever/2.5
B73="B73Ref4.fa"
LTR_retriever \
	-genome $B73 \
	-infinder ../01_ltrfinder/B73.finder.1.scn \
	-inharvest ../02_ltrharvest/B73.harvest.scn \
	-nonTGCA ../02_ltrharvest/B73.harvest.nonTGCA.scn \
	-threads 8

The job failed due to the following error:
Dependency checking: The RMblast engine is not installed in RepeatMasker!
There is one output file generated, which is dummy060817.fa.946456.

Then I run the command:
RepeatMasker -e ncbi -q -pa 1 -no_is -norna -nolow dummy060817.fa* -lib dummy060817.fa*
Here is the output: (I need to load module repeatmasker/4.0.3 or repeatmasker/4.0.5)

dummy060817.fa.946456.masked  
dummy060817.fa.946456.nsq      
dummy060817.fa.946456.tbl
dummy060817.fa.946456      
dummy060817.fa.946456.nhr     
dummy060817.fa.946456.ori.out
dummy060817.fa.946456.cat  
dummy060817.fa.946456.nin     
dummy060817.fa.946456.out

I am running on the supercomputer of my university.

Thanks for your help!

Ying

**Comment by oushujun** [comment]
Hi Ying,

The output confirms that you have RepeatMasker in your HPC, however LTR_retriever is complaining the missing of RepeatMasker, which means the RepeatMasker path is not properly passed down to LTR_retriever. You may need to double check the installation of LTR_retriever. If you didn't change the path file and rely on finding denpendent programs from bash, then you also need to load RepeatMasker to your job.

>module load repeatmasker/4.0.5
module load ltrretriever/2.5
B73="B73Ref4.fa"
LTR_retriever 
-genome $B73 
-infinder ../01_ltrfinder/B73.finder.1.scn 
-inharvest ../02_ltrharvest/B73.harvest.scn 
-nonTGCA ../02_ltrharvest/B73.harvest.nonTGCA.scn 
-threads 8

Best,
Shujun
