### ISSUE TITLE
RepeatMasker: line 28: 25891 Segmentation fault

### ISSUE THREAD

**Issue by zhaoruolan** [oushujun/LTR_retriever#52]
(LTR_retriever) [00:07:33]rzhao@magnus-2:~/LTR_retriever$ 'LTR_retriever -genome /scratch/pawsey0149/rzhao/wheatProject/LTR_file/refKA_polished/refKA_polished.fasta'

##########################
##########################

Contributors: Shujun Ou, Ning Jiang

For LTR_retriever, please cite:

	Ou S and Jiang N (2018). LTR_retriever: A Highly Accurate and Sensitive Program for Identification of Long Terminal Repeat Retrotransposons. Plant Physiol. 176(2): 1410-1422.

For LAI, please cite:

	Ou S, Chen J, Jiang N (2018). Assessing genome assembly quality using the LTR Assembly Index (LAI). Nucleic Acids Res. 2018;46(21):e126.

Parameters: -genome /scratch/pawsey0149/rzhao/wheatProject/LTR_file/refKA_polished/refKA_polished.fasta

Fri Aug 23 00:14:17 AWST 2019	Dependency checking: The RMblast engine is not installed in RepeatMasker!

---------------------------------
I checked the RepeatMasker library, the taxonomy.dat is not zipped. 

Then I got the following message after running 'RepeatMasker -e ncbi -q -pa 1 -no_is -norna -nolow dummy060817.fa* -lib dummy060817.fa*'

group/pawsey0149/rzhao/anaconda/envs/LTR_retriever/bin/RepeatMasker: line 28: 25891 Segmentation fault      (core dumped) perl /group/pawsey0149/rzhao/anaconda/envs/LTR_retriever/share/RepeatMasker/${NAME} $@

------------------------------------
Do you know how to solve this problem?

Many thanks,
Ruolan

**Comment by oushujun** [comment]
Dear Ruolan,

Please reinstall RepeatMasker either conda or manually. You may want to try this conda repository:
`conda install -c bioconda repeatmasker`

Or try older versions of RepeatMasker available on conda:
https://anaconda.org/bioconda/repeatmasker/files
eg. `conda install -c bioconda repeatmasker=4.0.8`

Hope this helps!

Shujun

**Comment by zhaoruolan** [comment]
> RepeatMasker
Dear Shujun:

Problem solved!
My supervisor told me to run ./configure under RepeatMasker.
I followed the steps, then filled in the paths under LTR_retriever with the paths of those modules. Now I can pass the dependency check. 

Many thanks,
Ruolan
