### ISSUE TITLE
Differences between LTR-retriever and RepeatMasker

### ISSUE THREAD

**Issue by xiaenhua** [oushujun/LTR_retriever#53]
Dear Shujun,
Thanks for developing LTR_retriever. I used LTR_retriever to annotate a subset sequences of a plant genome and found 2333 intact LTR-RTs. This number is much less than that annotated by RepeatMasker (approximate 11743 ) with non-redundant LTR-RTs reported by LTR_retriever. How to explain such differences? Which datasets should I use for downstream analysis? BTW, I only focus on the evolution of LTR-RTs.

With kind regards,

Enhua

**Comment by oushujun** [comment]
Dear Enhua,

I forgot if I have replied to your question or not. Sorry if I missed it.
LTR_retriever identifies **intact** LTR retrotransposons, which usually a small fraction of all LTR sequences (intact, solo LTR, truncated, fragmented, remnants, LTR-like...) that are annotated by RepeatMasker. The two datasets represent different aspects of a genome and using which depends on your analysis. Hope this helps!

Best,
Shujun
