### ISSUE TITLE
Some errors about  :LAI is not applicable on the current genome assembly

### ISSUE THREAD

**Issue by 123guoxiaoyu** [oushujun/LTR_retriever#57]
Hello,
I am running LTR retriever, and I am coming across these errors:
1.when i run /LTR_retriever/LTR_retriever,It displays the following error, but it can continue to run.
Fri Oct 25 06:19:16 Local time zone must be set--see zic manual page 2019       1 truncated LTR-RTs found
Warning: LOC list /dellfsqd2/ST_OCEAN/USER/zhangrui/test/guo/Flow_test/rawdata/smdlt_test.part-1.fa.ltrTE.veryfalse is empty.
2.finally,it displays the following error,I want to know whether the reason for this error is that there are too few LTRs in my input file, or there is a problem with my operation.
Fri Oct 25 06:31:10 Local time zone must be set--see zic manual page 2019       The identity of LTR sequences: 88.7317261904762%

                                【Warning】 The identity drops below the safe limit. Instead, identity of 92% will be used for LAI adjustment.

Fri Oct 25 06:31:10 Local time zone must be set--see zic manual page 2019       Calculate LAI:

                                【Error】Intact LTR-RT content (0.02%) is too low for accurate LAI calculation (min 0.1% required)
                                【Error】 Total LTR sequence content (0.3%) is too low for accurate LAI calculation (min 5% required)

                                Sorry, LAI is not applicable on the current genome assembly.

Fri Oct 25 06:31:13 Local time zone must be set--see zic manual page 2019       All analyses were finished!
3.(1)Here are example commands that lead to the error：
./ltr_finder -D 15000 -d 1000 -L 7000 -l 100 -p 20 -C -M 0.8 ./rawdata/smdlt_test.fa > ./rawdata/smdlt.finder.scn
(2)./LTR_retriever -threads 4 -genome ./rawdata/1.fa -infinder ./rawdata/1.finder.scn
my input file is a whole genome.fa
Any ideas as to what the issue is? Thank you!

**Comment by oushujun** [comment]
Hello,

If you have not, please update LTR_retriever to v2.7 and try again.

Please use the Arabidopsis genome to test on the pipeline and make sure
it's correctly installed.

If you are testing the pipeline with a small subset of your data, try to
run it on the full set. It's pretty quick. The wheat genome took 8 days.

If it works properly, and still says limited intact LTR and total LTR,
that's what it literally means. Not all species has abundant and avtive LTR
retrotransposons.

Hope these helps!

Best,
Shujun

**Comment by 123guoxiaoyu** [comment]
Hi Shujun,
Thank you for your reply!
After I tried the way you said, I was very happy and solved the problem.
Thanks again!
Regreet
xiaoyu
