### ISSUE TITLE
LTR_Retriever RMBlast not installed

### ISSUE THREAD

**Issue by RadeshNMP** [oushujun/LTR_retriever#58]
Dear Shujun,

I am trying to run the LTR_Retriever to generate the LAI for a plant genome. When I tried to run the LTR_Retriever using the input of the LTR_harvest, I got the below error message regarding the RMblast. 

Parameters: -genome /work/lianglab/wgs/lavender/LA_genome_final.fa -inharvest ../LA_ltrharvest_output -v

Wed Nov  6 15:04:36 EST 2019    Dependency checking: The RMblast engine is not installed in RepeatMasker!

I have run RepeatMasker before and I did not have any issues with it. Please let me know your thoughts and suggestions to get past this issue.

Thank you,
Radesh

**Comment by oushujun** [comment]
Hi Radesh,

Sorry for the delay reply. This tells that the RepeatMasker does not have the -engine ncbi installed, which is RMblast. You may want to reinstall RepeatMasker or provide a version that has RMblast installed. The conda version v4.0.9_p2 works for me.

Best,
Shujun

**Comment by oushujun** [comment]
#43

**Comment by oushujun** [comment]
Closed due to inactivity. Please reopen it if you still have the issue.
