### ISSUE TITLE
perl: symbol lookup error

### ISSUE THREAD

**Issue by wuxiaopei0509** [oushujun/LTR_retriever#59]
Hi,shujun
When I use LTR_retriever to identify the LTR-RT derived from LTR-finder and LTR-harvest,it did not produce results what we want. I check the log file and found 
perl: symbol lookup error: /home/wuxiaopei/perl5/lib/perl5/x86_64-linux-thread-multi/auto/threads/threads.so: undefined symbol: Perl_Istack_sp_ptr
Thu Nov 14 12:30:32 CST 2019    Intact LTR-RT found: 0

cp: cannot stat `luzhudujuan.fa.mod.retriever.scn.adj': No such file or directory
Thu Nov 14 12:30:32 CST 2019    No LTR-RT was found in your data.

Thu Nov 14 12:30:32 CST 2019    All analyses were finished!

where is the problem?Can you help me?

**Comment by oushujun** [comment]
Hi, can you paste the complete log here? Thanks! -Shujun

**Comment by oushujun** [comment]
Hi @wuxiaopei0509 ,

From a google search, you may have mixed perl versions installed in your system.
Ref: https://www.perlmonks.org/?node_id=832773
Please reinstall Perl using conda.

Best,
Shujun

**Comment by oushujun** [comment]
Closed due to inactivity. Please reopen it if you still have the issue.

**Comment by zillurbmb51** [comment]
Hello, I am having same problem. I removed perl using both yum and conda and then installed again using conda. But nothing happens. Any Help? Best, Zillur

**Comment by wuxiaopei0509** [comment]
sorry ,  Zillur 
I have forgotten how to deal with it at last ,maybe you can install perl and LTR_retriever in the same conda env . Please create a new conda env and don't install in the base env .
Best!
