### ISSUE TITLE
The total number of LTR in Arabidopsis

### ISSUE THREAD

**Issue by wzhjlau2009** [oushujun/LTR_retriever#60]
Hi , Shujun
Thanks for so powerful tools, and recently i use LTR_retrieve to identify the LTR-RT from LTR_finder and harvest in Arabidopsis(TAIR10) genome , it works well and i get the results.  But only 184 intact LTR_RT are identified in the pass.list file. I think the number is maybe too small for whole Arabidopsis genome.  I will very happy if you give me some advice about what led to this results ? Thanks!
[TAIR10.fa.mod.pass.list.txt](https://github.com/oushujun/LTR_retriever/files/3885067/TAIR10.fa.mod.pass.list.txt)

**Comment by oushujun** [comment]
Hi @wzhjlau2009 ,

184 is a lower count of intact LTR-RTs I've got from the TAIR10 genome, but not surprisingly low. In a recent test (Aug 27, 2019) I got 194 intact LTR-RTs. To obtain raw candidates what parameters did you use?

Best,
Shujun

**Comment by wzhjlau2009** [comment]
Hi @Shujun
Thanks for your reply. You got 194 intact LTR-RTs , did it mean that only 194 intact LTR-RTs in the whole Arabidopsis genome ? Here is my parameters. 
![image](https://user-images.githubusercontent.com/6326115/69814307-e18aff80-122e-11ea-99dc-8559ed0cb6b3.png)

**Comment by oushujun** [comment]
Yes you are right. Only ~200 intact LTR elements in the Ath genome, which
has very little LTRs indeed. Your parameters looks ok. You may get slightly
more if lower similarity to 85%.

Best,
Shujun

**Comment by oushujun** [comment]
Hi @wzhjlau2009,

I recently identified a bug for dropping high-quality intact LTR elements. I fixed it and it could recover 5% more sensitivity for genomes with low LTR contents like Arabidopsis. The version is upgraded to v2.8 now. I identify 214 unique intact LTR elements with this version and 193 for v2.7.

I am drafting a new release with benchmarking results, please check it out when it becomes available.

Best,
Shujun

**Comment by wzhjlau2009** [comment]
Hi @oushujun ，
Thanks very much. By the way , How can i identified for all the LTR elements including solo LTR ? By RepeatMasker for denovo genome ?  Thanks for your advice! 

Best Wishes!

**Comment by oushujun** [comment]
By default the program will perform whole genome annotation, which is
basically RepeatMakser using the generated library with some extra
filtering. To find solo LTRs, you may use the soloLTR script in the bin
folder.

Best, Shujun

**Comment by wzhjlau2009** [comment]
Hi， @oushujun 
I see，recently i want to identify all kinds of LTRs in a denovo assembly genome. Your suggestions will help me a lot. Thank you very much!

Sincerely!

**Comment by oushujun** [comment]
I consider this issue resolved. Please reopen it if you find out it is not or open new issues.
