### ISSUE TITLE
Can't locate object method "end" via package "Thread::Queue" 

### ISSUE THREAD

**Issue by zhangleigloria** [oushujun/LTR_retriever#61]
Hi Shujun，
     I installed LTR_retriever with conda quickly，and the following error occurred.
     Parameters: -genome niechi.genome.fasta -inharvest niechi.harvest.scn -infinder niechi.finder.scn -t 8

Thu Jan  9 12:10:31 CST 2020    Dependency checking: All passed!
Thu Jan  9 12:11:16 CST 2020    LTR_retriever is starting from the Init step.
Thu Jan  9 12:13:42 CST 2020    Start to convert inputs...
                                Total candidates: 7568
                                Total uniq candidates: 7074

Thu Jan  9 12:15:40 CST 2020    Module 1: Start to clean up candidates...
                                Sequences with 10 missing bp or 0.8 missing data rate will be discarded.
                                Sequences containing tandem repeats will be discarded.

Thu Jan  9 12:17:27 CST 2020    4686 clean candidates remained

Thu Jan  9 12:17:27 CST 2020    Modules 2-5: Start to analyze the structure of candidates...
                                The terminal motif, TSD, boundary, orientation, age, and superfamily will be identified in this step.

Can't locate object method "end" via package "Thread::Queue" at ./LTR_retriever/bin/LTR.identifier.pl line 125.
Thu Jan  9 12:20:24 CST 2020    Intact LTR-RT found: 0

cp: cannot stat `niechi.genome.fasta.retriever.scn.adj': No such file or directory
Thu Jan  9 12:20:24 CST 2020    No LTR-RT was found in your data.

Thu Jan  9 12:20:24 CST 2020    All analyses were finished!

    Do you know why this problem occurs?Thank you very much!

**Comment by oushujun** [comment]
Hello,

Looks like your perl is not correctly installed. Please reinstall perl on
your conda env and try again.

Best,
Shujun

**Comment by oushujun** [comment]
I have changed the `perl` interpreter from `/usr/bin/perl` to using the `ENV` default. This should resolve the system restriction given your local perl is correctly installed. Please update `LTR_retriever` and try again.
