### ISSUE TITLE
LTR age using local TE library seq 

### ISSUE THREAD

**Issue by bioteksampath** [oushujun/LTR_retriever#64]
Hi oushujun,

wondering if you give suggestions on how to calculate age of LTRs from previously published genomes (wheat).

I have the TE gff (with complete and fragment information)  but I don't have 3' or 5' LTR position information. I like to calculate the age of each LTR, so wondering how can I use the local TE library in LTR retriever to get an age for each element?

Any suggestions would be helpful.

Thanks
sam

**Comment by oushujun** [comment]
Hi Sam,

You can extract the intact LTR sequence from the gff, do a self blast for each sequence, within each blast result, you may find the pairing of the 5' and 3' LTR and the identity between them, then use this equation to calculate the age: T = (1- iden%) / 2µ with µ being the mutation rate you prefer.

Hope this helps!

Best,
Shujun

**Comment by oushujun** [comment]
Close for now due to inactive. Please reopen if you have more questions.
