### ISSUE TITLE
the numbers and bps of all LTRs 

### ISSUE THREAD

**Issue by Dobkin-Sun** [oushujun/LTR_retriever#66]
Dear Shujun,

Hello!Thanks for developing this software! I extracted 935179 LTRs , which have 1263197104 bps(~49.98%) in total. I got this result with ' .mod.out.gff' file. But I notice that the output files contain a file named '.mod.out.LTR.distribution.txt'. It tells me that the percentage of all LTRs in whole genome is  46.60%.So I want to know which result is reliable. 
And my  result is  from  '.fasta' file  not  '.mod.fasta' with 'gff' file. So there is a problem if I am wrong?
Any suggestions would be helpful.

Best
Sun Daojin

**Comment by oushujun** [comment]
Dear Daojin,

Thank you for the report, there was a small bug when doing different counts, neither of these counts is accurate. I have fixed this bug in the new push.

Please rerun these two lines in your folder and you will get the consistent and updated result:
`perl $script_path/LTR_retriever/bin/LTR_sum.pl -genome $genome -all $genome.out > $genome.out.LTR.distribution.txt`
`perl $script_path/LTR_retriever/bin/make_gff3_with_RMout.pl $genome.out`

Best,
Shujun

**Comment by Dobkin-Sun** [comment]
Dear Shujun,
Thank you for replying! I have tried your new version "2.8.6". When I installed RepeatMasker ,it repoerted "Dependency checking: The RMblast engine is not installed in RepeatMasker!". But I solved this problem by install Text Soudex by CPAN.
It seemed all right.But when I used the latest software, the last one of this workflow got stuck.I checked the output files.I only found the 'gff3' file and have not 'gff' file.I noticed that my CPU was occupied 100% in 48 hours and then the computer could not work.I have no choice but to reboot.So I want to know why the annotation process can not work.
Best
Sun Daojin

**Comment by oushujun** [comment]
Hi Daojin,

You don't need to reinstall the dependencies. By going into the LTR_retriever folder you can simply run `git pull` then the update is finished. To fix your current issue, you may run `conda install -n LTR_retriever -c bioconda ltr-retriever`.

Best,
Shujun

**Comment by Dobkin-Sun** [comment]
Thanks a lot Dr Ou.
