### ISSUE TITLE
"?" strand direction in 'gff3'

### ISSUE THREAD

**Issue by Dobkin-Sun** [oushujun/LTR_retriever#69]
Dear Shujun,
After using v2.8.6,I found a problem about the gff3 file. First, the first eight annotations of gff3 don't have  'seqid' information. And the ninth annotion has a 'Boutg12958_pilon_' seqid which doesn't exist in source fasta file. The beginning of 'Boutg' looks like that the annotation of intact LTR went wrong.
Second, lots of annotations don't have correct strand direction of "+" or "-" and there are a lot of directions of "?" in file.
Best
Sun Daojin

**Comment by oushujun** [comment]
Hi Daojin,

Your source file may have complex sequence names and the program automatically shorten the name for you. You may want to do it yourself to make the downstream easier.
This thread can answer your second question: https://github.com/oushujun/EDTA/issues/80

Best,
Shujun

**Comment by Dobkin-Sun** [comment]
Thank you again, Dr Ou.
