### ISSUE TITLE
Are those percentages or decimals for Intact and total LTR in the LAI ouputs

### ISSUE THREAD

**Issue by linzhi2013** [oushujun/LTR_retriever#70]
Hi Shujun,

I noticed this *Although LAI is independent of total LTR-RT content, estimation of LAI is empirically not accurate when total LTR-RT content is less than 5% and intact LTR-RT content is less than 0.1%*

Here is the first two lines output by the `LAI` command:
```
Chr	From	To	Intact	Total	raw_LAI	LAI
whole_genome	1	1065919434	0.0382	0.5002	7.64	8.94
```

I am curious about whether the *0.0382* or *0.5002*   is a percentage or just a decimal? If it is a percentage, that would mean 0.0382% < 0.1% and I should not apply LAI to my genome.

The command I used:
```
/nextomics/Software/Annotation/SOFTWARE//LTR_retriever/LAI \
 -genome genome.all.fasta \
 -intact genome.all.fasta.pass.list \
 -all /export/path/toRepeatMasker/result/test.out -t 20

```

The logs:

```
Fri May 22 12:16:59 CST 2020	Dependency checking: Passed!
Fri May 22 12:16:59 CST 2020	Calculation of LAI will be based on the whole genome.
				Please use the -mono parameter if your genome is a recent ployploid, for high identity between homeologues will overcorrect raw LAI scores.
Fri May 22 12:16:59 CST 2020	Estimate the identity of LTR sequences in the genome: standard mode
Fri May 22 18:50:58 CST 2020	The identity of LTR sequences: 93.5383103979807%
Fri May 22 18:50:58 CST 2020	Calculate LAI:

						Done!
```

Thank you in advance!

All the best
Guanliang

**Comment by oushujun** [comment]
Hi Guanliang,

It's in decimal. "0.0382	0.5002" means the genome has 3.82% of intact LTR-RT and 50.02% LTR sequences in total. Your command and log look good to me except the LTR identity is a bit high. Is this a polyploid species?

Best,
Shujun
