### ISSUE TITLE
LAI is much lower than raw_LAI

### ISSUE THREAD

**Issue by bitezhu** [oushujun/LTR_retriever#71]
Hi，shujun
I am running the LAI index on a newly assembled genome (less than 200Mb). The contiguity is pretty good with N50>1.2Mb.
I have the following results :
Chr     From    To      Intact  Total   raw_LAI LAI
whole_genome    1       178823252       0.0298  0.1554  19.16   13.53

I put my full commands here:
~/toolkit/LTR_Finder/source/ltr_finder -D 15000 -d 1000 -L 7000 -l 100 -p 20 -C -M 0.9   genome_10k_pilon.fa > TAIR10.finder.scn
~/toolkit/gt-1.5.10-Linux_x86_64-64bit-complete/bin/gt suffixerator -db genome_10k_pilon.fa -indexname 248_gt -tis -suf -lcp -des -ssp -sds -dna
~/toolkit/gt-1.5.10-Linux_x86_64-64bit-complete/bin//gt ltrharvest -index 248_gt  -minlenltr 100 -maxlenltr 6000 -mindistltr 1500 -maxdistltr 25000 -similar 95 -mintsd 4 -maxtsd 6 -motif tgca -vic 10 -seqids  yes > genome.fa.harvest.scn
~/toolkit/LTR_retriever-master/LTR_retriever -genome genome_10k_pilon.fa -inharvest genome.fa.harvest.scn -infinder TAIR10.finder.scn -threads 24

The difference between raw_LAI and LAI really confuses me. According to the equation in your paper, 'LAI = raw LAI + 2.8138 × (94 – whole genome LTR identity). ', it seems  raw_LAI should always be smaller than LAI. So I wonder what causes the drop of LAI value.

Thanks in advance for your reply!

**Comment by oushujun** [comment]
@bitezhu It depends on how active were the LTR retrotransposons in your genome. The LTR identity can approximate this value. In the equation you referenced, if LTR identity goes beyond 94, the corrected LAI will be lower than the raw LAI. This value is recorded in the `*.iden` file. Overall LAI of 13.5 is not bad at all.

Best,
Shujun

**Comment by bitezhu** [comment]
@oushujun So higher LTR identity means this species went through LTR expansion recently?

**Comment by oushujun** [comment]
> @oushujun So higher LTR identity means this species went through LTR expansion recently?

Yup.

**Comment by xingjianfeng100** [comment]
> @bitezhu It depends on how active were the LTR retrotransposons in your genome. The LTR identity can approximate this value. In the equation you referenced, if LTR identity goes beyond 94, the corrected LAI will be lower than the raw LAI. This value is recorded in the `*.iden` file. Overall LAI of 13.5 is not bad at all.
> 
> Best, Shujun

https://github.com/oushujun/LTR_retriever/issues/83#issuecomment-891476355


@oushujun Then may I ask, which LAI value might I use for interspecific comparison? Should I choose the raw LAI for interspecific comparison in this case?

**Comment by oushujun** [comment]
@xingjianfeng100 please read the LAI manual or the paper :)

**Comment by xingjianfeng100** [comment]
@oushujun Thank you, well,  in normal situations, the LAI is robust for interspecific comparison;  actually I would  like to know, when  LTR identity goes beyond 94, does it mean adjusted LAI is a overcorrection index, and we should abandon it in this situation?
