### ISSUE TITLE
Error: the pre-library file is empty

### ISSUE THREAD

**Issue by vtartaglio** [oushujun/LTR_retriever#74]
Hello,

I am running LTR_retriever on a new accession of the grass Brachypodium. (I ran LTRHarvest on the masked genome because I want to identify novel LTR-RTs that aren't in RepBase.) I have run LTR_retriever successfully before, but with this particular genome I am getting the following error. Let me know what other information you need from me, and if you'd like to see the contents of any of the intermediate files. Thanks!

##########################
##########################

Contributors: Shujun Ou, Ning Jiang

For LTR_retriever, please cite:

Ou S and Jiang N (2018). LTR_retriever: A Highly Accurate and Sensitive Program for Identification of Long Terminal Repeat Retrotransposons. Plant Physiol. 176(
2): 1410-1422.

For LAI, please cite:

Ou S, Chen J, Jiang N (2018). Assessing genome assembly quality using the LTR Assembly Index (LAI). Nucleic Acids Res. 2018;46(21):e126.

Parameters: -genome ABR113.knownTEsmasked.fasta -inharvest ABR113.result85 -threads 31

Sat Jun  6 18:08:49 PDT 2020    Dependency checking: All passed!
Sat Jun  6 18:09:59 PDT 2020    LTR_retriever is starting from the Init step.
Sat Jun  6 18:10:15 PDT 2020    Start to convert inputs...
                                Total candidates: 2287
                                Total uniq candidates: 2287

Sat Jun  6 18:10:41 PDT 2020    Module 1: Start to clean up candidates...
                                Sequences with 10 missing bp or 0.8 missing data rate will be discarded.
                                Sequences containing tandem repeats will be discarded.

Sat Jun  6 18:11:13 PDT 2020    157 clean candidates remained

Sat Jun  6 18:11:13 PDT 2020    Modules 2-5: Start to analyze the structure of candidates...
                                The terminal motif, TSD, boundary, orientation, age, and superfamily will be identified in this step.

Sat Jun  6 18:12:36 PDT 2020    Intact LTR-RT found: 1

Sat Jun  6 18:12:55 PDT 2020    Module 6: Start to analyze truncated LTR-RTs...
                                Truncated LTR-RTs without the intact version will be retained in the LTR-RT library.
                                Use -notrunc if you don't want to keep them.

Sat Jun  6 18:12:55 PDT 2020    0 truncated LTR-RTs found
Sat Jun  6 18:12:55 PDT 2020    0 truncated LTR sequences have added to the library

Sat Jun  6 18:12:55 PDT 2020    Module 5: Start to remove DNA TE and LINE transposases, and remove plant protein sequences...
                                Total library sequences: 3
Sat Jun  6 18:13:08 PDT 2020    Retained clean sequence: 0

ERROR: 1 intact LTR-RTs have found, but the pre-library file ABR113.knownTEsmasked.fasta.ltrTE is empty.
Something is wrong at this point. Please report the bug to https://github.com/oushujun/LTR_retriever/issues
Program halt!

**Comment by oushujun** [comment]
Masking the genome beforehand will breakdown intact LTR elements even they are novel. This is probably the reason you only found 1 intact LTR. To find new LTR sequences, I suggest the other way around: scan the unmasked genome with LTR_retriever, then mask the de novo library with your curated library. The unmasked sequences are new.

Shujun
