### ISSUE TITLE
Something wrong with "-misschar"

### ISSUE THREAD

**Issue by Zea1nfO** [oushujun/LTR_retriever#78]
Hi, shujun
I wanna use LAI to evaluate my genome assembly.
And i do as you said [here](https://github.com/oushujun/LTR_retriever) .
When i pass all the depency checking, i got a error message like this:
**Can't exec "-misschar": No such file or directory at /my_paths_to/LTR_retriever/bin/cleanup.pl line 61.
Use of uninitialized value $tandem in substitution (s///) at /my_paths_to/LTR_retriever/bin/cleanup.pl line 62.**

But the ltr_retriever is still running.
Mabye this message is not so important?
Or can you tell me how to fix it?
Thanks a lot.

**Comment by Zea1nfO** [comment]
Hi, shujun
I think i got the cause of this issue.
In this [cleanup.pl](https://github.com/oushujun/LTR_retriever/blob/master/bin/cleanup.pl), the trf path is not rightly set here.
I just replace the trf path with my absolute  path in the cleanup.pl.
And the error message is seemed to be gone.
best regards

**Comment by oushujun** [comment]
Thanks for finding the issue. This script should not be affected because in `LTR_retriever` it has a check to make sure TRF is working and the path is passed to all associated scripts including `cleanup.pl`. Anyways, I have fixed the $trf path issue in `cleanup.pl` by adding an extra check and it will show in the next update. 

Shujun

**Comment by Zea1nfO** [comment]
> Thanks for finding the issue. This script should not be affected because in `LTR_retriever` it has a check to make sure TRF is working and the path is passed to all associated scripts including `cleanup.pl`. Anyways, I have fixed the $trf path issue in `cleanup.pl` by adding an extra check and it will show in the next update.
> 
> Shujun

That`s great.
:)
