### ISSUE TITLE
Can i use "-noanno" options to accelerate the whole process?

### ISSUE THREAD

**Issue by Zea1nfO** [oushujun/LTR_retriever#80]
Hi, shujun

I have finish a LAI process today.
And i find there is a "Use -noanno if you don't want whole-genome LTR-RT annotation" message in log file.
So i wanna know that can i use this option to do LAI analysis?
Or this option is neccessary for LAI analysis?

Best regards

**Comment by oushujun** [comment]
Hello,

LAI needs whole-genome LTR annotation so if you use -noanno, there won't be
LAI results at the end. But you can always run LAI independently given
required inputs.

Best,
Shujun

**Comment by Zea1nfO** [comment]
@oushujun 
Thanks a lot. 
I got it.
Best regards.
:)
