### ISSUE TITLE
LAI for ployploid

### ISSUE THREAD

**Issue by Jiny000** [oushujun/LTR_retriever#83]
Hi,
I used LTR retriever to calculate LAI of wheat,which is an allohexaploid(AABBDD).I took all wheat genome into LTR retriever,and I want to get LAI for each subgenome.I use this command:
```sh
for i in `subgenomeA subgenomeB subgenomeD `
do
LAI -genome wheatCS.fa -intact genome.fa.pass.list -all genome.fa.out -mono $i.list
done
``` 
The genome file ,intact file and all(.out) file are generated by whole wheat genome.The subgenomeA/B/D.list is the name list of subgenome chromosome.Can I get the correct result of LAI?Need I extract each subgenome from genome file ,intact file and all(.out) file?

Sincerely

**Comment by oushujun** [comment]
Yes, this is the right way to calculate LAI for polyploid. Consider using `-totLTR` and `-iden` if you want to compare multiple genomes because these two values affect LAI pretty easily. You may use values from the "best" (in a subjective manner) genome as the standard and set it on other genomes.

**Comment by cassondranewman** [comment]
Hello, 
Thank you for creating this assembly metric! I wanted to ask- if you are comparing two polyploids of the same species (an intraspecific comparison) can you simply compare the whole-genome raw LAI score? 

In other words, if you are doing an intraspecific comparison of polyploids, does the corrected LAI score need to be computed per subgenome [as shown above] - or is comparing whole-genome raw LAI scores enough?

**Comment by oushujun** [comment]
Hi, yes, you may use raw LAI for intraspecific comparison. For polyploids,
you still need to calculate LAI values for each subgenome and the
comparison between same subgenomes can be done with raw LAI, but for
different subgenomes, you still need to use corrected LAI.

Best,
Shujun

**Comment by cassondranewman** [comment]
Thank you for the clarification! I appreciate it.
