### ISSUE TITLE
Can't exec "-misschar"

### ISSUE THREAD

**Issue by Qiuming1986** [oushujun/LTR_retriever#84]
Can't exec "-misschar": No such file or directory at LTR_retriever-master/bin/cleanup.pl line 61.
Use of uninitialized value $tandem in substitution (s///) at LTR_retriever-master/bin/cleanup.pl line 62.

The software has been installed, howerver the process of calculation has the issue.
And the results are as follow:
Wed Nov 11 00:36:01 CST 2020	Dependency checking: All passed!
Wed Nov 11 00:36:14 CST 2020	LTR_retriever is starting from the Init step.
Wed Nov 11 00:38:10 CST 2020	The longest sequence ID in the genome contains 48 characters, which is longer than the limit (15)
				Trying to reformat seq IDs...
				Attempt 1...
Wed Nov 11 00:38:29 CST 2020	Seq ID conversion successful!

Wed Nov 11 00:38:29 CST 2020	Start to convert inputs...
				Total candidates: 114885
				Total uniq candidates: 111063

Wed Nov 11 00:39:10 CST 2020	Module 1: Start to clean up candidates...
				Sequences with 10 missing bp or 0.8 missing data rate will be discarded.
				Sequences containing tandem repeats will be discarded.

Wed Nov 11 00:39:17 CST 2020	110948 clean candidates remained

Wed Nov 11 00:39:18 CST 2020	Modules 2-5: Start to analyze the structure of candidates...
				The terminal motif, TSD, boundary, orientation, age, and superfamily will be identified in this step.

Wed Nov 11 01:18:56 CST 2020	Intact LTR-RT found: 0

Wed Nov 11 01:18:56 CST 2020	No LTR-RT was found in your data.

Wed Nov 11 01:18:57 CST 2020	All analyses were finished!

**Comment by oushujun** [comment]
Hi @Qiuming1986 ,

To make sure the installation is correct, please test your LTR_retriever with this toy genome or other small plant genomes: https://github.com/oushujun/EDTA/tree/master/test

Best,
Shujun

**Comment by Qiuming1986** [comment]
Dear Shujun,

I'm sorry to disturb you. I could not resolve the problem of **Can't exec "-misschar"**. According to you suggestion, I have made the test. As you said, the installation is not correct. However, I don't know which software is not correct. RepeatMasker, HMMER, BLAST+, CDHIT or perl module? I would be much grateful if you could help me.

**Comment by oushujun** [comment]
Hi @Qiuming1986,

I don't know neither...without proper error messages. Most likely Repeatmasker is not properly installed. In this case I would suggest simply create a new conda env and install LTR_retriever fresh.

Best,
Shujun

**Comment by oushujun** [comment]
@Qiuming1986 have you resolve the issue? Thanks. -Shujun

**Comment by oushujun** [comment]
I am closing this thread for now. Please reopen it if your issue is not resolved. Thanks! - Shujun

**Comment by timkahlke** [comment]
Hi,

I had the same problem. Turns out it's missing Tandem Repeat Finder. Just install it and put it in the path.

The weird error message comes from calling cleanup.pl with an empty `-trf_path` option which then sets `$trf_path` to the next index of `@ARGV`, i.e. `-misschar`. Adding the check `and $ARGV[$k+1]!~/^-/` to each line in the `foreach @ARGV` block in cleanup.pl (as done in the other scripts) will change the error message to a meaningful `can't execute /.../trf409.legacylinux64. No such file or directory`.
