### ISSUE TITLE
assessing the performance of LTR_retriever

### ISSUE THREAD

**Issue by sadikmu** [oushujun/LTR_retriever#85]
Thanks for providing this powerful tool. 

I am interested to look at LTR from PacBio Reads vs assembly and hence no doubt in the importance of assessment metrics on the quality of output to get optimised result from various parameters. These parameters were described and indicated in the article: sensitivity, specificity, accuracy, and precision, but I couldn't find the script. 

Any help please?

**Comment by oushujun** [comment]
Hello,  please find the benchmark script here:

https://github.com/oushujun/EDTA#benchmarking

Best,
Shujun
