### ISSUE TITLE
source for database files

### ISSUE THREAD

**Issue by sarjopp** [oushujun/LTR_retriever#89]
What is the origin of Tpases020812DNA and Tpases020812LINE? In addition to citing LTR_retriever, I'd like to be able to cite the source of these. The Tpases020812DNA appears to be the same file used in the "Advanced repeat library" tutorial for MAKER, but there is no source given there either.

Thanks,
Sara

**Comment by oushujun** [comment]
Hi Sara,

These libraries were obtained from the MAKER-P paper (Campbell et al.,
2014). You may cite it to give credits. Thanks for the efforts!

Best,
Shujun

**Comment by sarjopp** [comment]
Thank you for the info, and for the great innovations of LTR retriever!
