### ISSUE TITLE
Can't exec "-misschar"

### ISSUE THREAD

**Issue by xiaoyezao** [oushujun/LTR_retriever#91]
Hi Shujun,

I encountered the following error message:

```
Can't exec "-misschar": Permission denied at /PARA/pp427/app/ltr_retriever-2.9.0/bin/cleanup.pl line 61.
Use of uninitialized value $tandem in substitution (s///) at /PARA/pp427/app/ltr_retriever-2.9.0/bin/cleanup.pl line 62.

```
and many others:

```
Use of uninitialized value $lLTR_start in numeric lt (<) at /PARA/pp427/app/ltr_retriever-2.9.0/bin/make_gff3.pl line 55, <List>
Use of uninitialized value $rLTR_end in numeric lt (<) at /PARA/pp427/app/ltr_retriever-2.9.0/bin/make_gff3.pl line 55, <List> l
Use of uninitialized value $chr in concatenation (.) or string at /PARA/pp427/app/ltr_retriever-2.9.0/bin/make_gff3.pl line 63, 
```
Are these serious problems? How to fix them?

Tao

**Comment by xiaoyezao** [comment]
Following the issues mentioned above, the job seems finished successfully, but with more warnings (see the attached log file)

What's wrong going here? Any suggestions?

[slurm-4637302.out.txt](https://github.com/oushujun/LTR_retriever/files/6396431/slurm-4637302.out.txt)

**Comment by oushujun** [comment]
Have you tried on a simple genome or simplify the sequence names? -Shujun
