### ISSUE TITLE
Dependency checking: The RMblast engine is not installed in RepeatMasker

### ISSUE THREAD

**Issue by Prabhu89-code** [oushujun/LTR_retriever#92]
Dear OuShuJun,
        I am trying to use LTR_retriever. I have encountered the "Dependency checking: The RMblast engine is not installed in RepeatMasker" issue.

Yes, I followed the posts on same issue. Though I tried all I cannot solve it.

My question is how to INSTALL "RMBlast". May be my RMBlast installation could be wrong.

What I done was,

1. Downloaded the linux version of rmblast,
2. Extracted tar file into rmblast-2.11.0 it in /usr/local/ and another time in the repeatmasker folder.
3. After extraction do we need to give any comment for installation or simply invoke the path during RepeatMasker run/rerun process.

Kindly help me to solve this issue.

Thanking you!

**Comment by oushujun** [comment]
Hello, the easiest way is to install conda, then use conda to install
LTR_retriever and dependencies.

Best,
Shujun

**Comment by Prabhu89-code** [comment]
Yes, I tried both manual and conda for LTR_retreiver. Both have resulted with issue on "RMblast engine is not installed in RepeatMasker".

**Comment by oushujun** [comment]
Did you create an isolated env for conda? If you  continuously encounter
the repeatMasker issue, you may reinstall repeatMasker in the conda env and
LTR_retriever should be able to pick it up automatically.

Shujun

**Comment by Prabhu89-code** [comment]
Dear Dr. OuShuJun,
        Thank you for your reply.
        
         I don't really understand what is "isolated env for conda" ?

I done LTR conda version installation as follows:

conda create -n LTR_retriever
source activate LTR_retriever
git clone https://github.com/oushujun/LTR_retriever.git
./LTR_retriever/LTR_retriever -h

For installation of repeatmasker using CONDA always failed.
So I downloaded "repeatmasker"
extract it
perl ./configure 
and give all the dependencies path.

In case of rmblast, I extracted it in /usr/local/RepeatMasker.

Could kindly correct me what I have done wrongly ?

Thank you very much !

Regards,
Prabhu, S

**Comment by oushujun** [comment]
After source activate, did you do the installation with conda install -c
bioconda ltr_retriever?

**Comment by Prabhu89-code** [comment]
Yes I done conda install -c bioconda ltr_retriever.

It prepared another folder in the LTR_env as "LTR_retriever" and installed  with database, bin, LTR_retreiver etc... folders

**Comment by Prabhu89-code** [comment]
Dear Dr.Ou Shu Jun,
        I successfully run the LTR_Retriever. I overcome the RMBlast dependency issue by following strategy posted from other comments in your github.

conda create -n EDTA python=3.6
conda activate EDTA
conda install -y -c anaconda biopython pandas glob2 scikit-learn=0.19.0
conda config --add channels conda-forge
conda config --add channels biocore
conda config --add channels bioconda
conda install -y -c cyclus java-jdk
conda install -y repeatmodeler repeatmasker
git clone https://github.com/oushujun/EDTA
./EDTA/EDTA.pl
  
I add path of EDTA bin (where all the dependencies are installed) to bash and run the LTR_Retriever. 
It is successfully running.
Afterwards, I will do analysis of LTR results.
If you are ok, can I send you mail regard analysis o LTR results ?

Thanking you!

Regards,
Prabhu, S

**Comment by oushujun** [comment]
Hi Prabhu,

I am glad you found the way that works! I would like to keep discussions on github as much as possible so that other people can benefit from it just like you did from other discussions. I am closing this issue since it's resolved. Please open new issues for new questions.

Best,
Shujun
