### ISSUE TITLE
sequence ID length limit constraint

### ISSUE THREAD

**Issue by anandksrao** [oushujun/LTR_retriever#93]
In LTR_retriever, is it possible to suppress the sequence ID length limit constraint of 15 characters?
If yes, then is it possible for end-user to do something simple like comment out a line in your code?
Please advise. Thanks!

**Comment by oushujun** [comment]
The length limit is imposed by rmblast. So wherever rmblast is used, ie.
RepeatMasker, blastn, blastx, there is a length limit on the sequence IDs.

- Shujun
