### ISSUE TITLE
Reg. Copia, Gypsy, and Unknown or total LTR density calculation

### ISSUE THREAD

**Issue by Yedomon** [oushujun/LTR_retriever#94]
Dear Dr. Shu Jun Ou,
         I have predicted the Copia, Gypsy, and Unknown. However, when I tried  to map the identified repeats alongwith cds using RIdeogram for 50Kb size, repeats show very less density.
        For eg.,
kb        Gene      LTR
1-50        3          0
51-100    8          0
101-150  10        0
151-200   9         0
201-250   8         0
251-300   11       0
301-350   9         0
351-400   9         1
........
I think for calculating LTR density we need to use different strategies. Though it is not directly related to the LTR_retriever, could you kindly help to figure out how to use LTR_retriever data for calculating Copia, Gypsy, and unknown for sliding windows of 50 kb with 25 kb step size.

Thanking you!

Regards,
Prabhu, S

**Comment by oushujun** [comment]
You can use the gff3 file and R to do so. Please make sure you are
summarizing the base pairs but not pieces of fragments in your window.

Shujun

**Comment by Prabhu89-code** [comment]
Dear Dr . Shu Jun,
         I am using LTR_retreiver to calculate the followings,
1. LTR location along the chromosome length (for density mapping),
2. Insertion time of identified LTRs,
3. Percentage of LTRs in the genome and percentage of Copia, Gypsy in the identified LTRs.

For 1st query I used, xxxx.LTR.gff3 file.
For 2nd I used xxxx.pass.list.gff3 (intact) and nmtf.pass.list (Non-TGCA). 
Now to calculate the percentage, which one I should use. I believe xxxx.LTR.gff3 is correct but it is not the same with intact and non-TGCA files. Locations are more frequent than the intact and non-TGCA files. Numbers and locations are different between each other.

Also percentage calculated in the xxx.out.superfam.size is not matching when we calculate manually with the bps/total bp of genome. Is bps means total "base pairs" of copia, gypsy, and unknown in the given genome ?

could you kindly clarify above my doubts on usuage of LTR_retriever results. I hope I am not burdening you.

Thanking you!

Regards,
Prabhu, S

**Comment by oushujun** [comment]
Hi Prabhu,

The gff3 file is for genome visualization not for summary, because there are nested elements and overlapping annotations in the file and will result in overestimation if simply adding things up.

For 2, are you sure you just want to look at non-TGCA LTRs? These are quite rare (~1% frequency).

For 3, you may need to write your own code for such a summary. You can check out RIdeogram or similar, and modify their code for your purpose.

Shujun

**Comment by Prabhu89-code** [comment]
Dear Dr. Shu Jun,
         Thank you for your reply.
         I understand first and second answers.
         For calculating precentage of Copia, Gypsy, and Unknown in the whole genome, which file I should use ? is xxx.LTR.gff3 is enough ?  Because file with xxx.out.superfam.size is not matching with the manual calucation. 

Thanking you!

Regards,
Prabhu, S

**Comment by oushujun** [comment]
xxx.LTR.gff3 is enough. 
As I mentioned in the previous reply, xxx.out.superfam.size considered nested insertion and overlapping. Manual calculation tends to overestimate.

**Comment by Prabhu89-code** [comment]
![LTR_retriever_eg](https://user-images.githubusercontent.com/54341159/123744790-377fc780-d8ea-11eb-939b-6681493df8a6.jpg)

Dear Dr. Shu Jun,
         Here I have attached the image of file which I am planning to calculate the Copia and Gypsy over the chromosome.
1.         In this case am I right to map as follows,
Copia   1-50kb       5         Gypsy 1-50kb       1
Copis    51-100kb  9        Gypsy  51-100kb    7

2. What is column 6 stands for (which I have highlighted in yellow).
3. Is there any ways to calculate insertion period of LTRs in xxx.LTR.GFF3 or it is only possible for intact and non-TGCA LTRs.

Thanking you!

Regards,
Prabhu, S

**Comment by Prabhu89-code** [comment]
Dr. Shu Jun,
      Could you please also clarify what is the difference between "intact TGCA LTR" in xxxx.pass.LIST and "LTR" present in xxx.LTR.GFF3 files. It will be very much helpful for preparing manuscript.

Thanking you!

Regards,
Prabhu, S

**Comment by oushujun** [comment]
The gff3 file contains both stucturally intact and fragmented LTRs. The
last tag At the last column tells that info. "homology" means annotated
using RepeatMasker. The pass.list file only contains intact LTRs which
could be used to calculate insertion time.

 Column 6 is alignment score if I remember correctly.

The number of fragmented LTRs can not represent the number of LTR
insertions. Please see other discussions.

Shujun

**Comment by Prabhu89-code** [comment]
![Gypsy_Copia_Landscape](https://user-images.githubusercontent.com/54341159/123928302-c19e5d80-d9c8-11eb-9c27-493260e35d1b.jpg)

My goal is to make figure like the above. So I would like to choose the correct result to plot the Copia and Gypsy landscape on the chromosome. Could you kindly let me know, which file I need to choose to measure the density of Copia and Gypsy.

Thanking you!

Regards,
Prabhu, S

**Comment by oushujun** [comment]
Hi Prabhu,

It depends on your research goal. If you want to visualize the abundance of
intact LTR elements, then use the intact.list; if you want to visualize all
LTR abundance, then you should use the whole-genome LTR annotation (gff3).
You probably want to calculate the percentage not count, because they have
very different lengths.

Best,
Shujun

**Comment by Prabhu89-code** [comment]
Dear Dr. Shu Jun,
         Thank you very much for your answer. I got clarification. I will use .gff3 result for landscape of all copia and gypsy in chromosome.

Thanking you!

Regards,
Prabhu, S
