### ISSUE TITLE
truncted LTR

### ISSUE THREAD

**Issue by xiaoyezao** [oushujun/LTR_retriever#96]
Hi Shujun,

I am wondering is it possible to generate the truncated LTR list like what `solo_finder.pl` does?

Another question is that in the log file, it says:
```
Thu Apr 29 18:24:01 CST 2021    3962 truncated LTR-RTs found
Thu Apr 29 19:07:05 CST 2021    233 truncated LTR sequences have added to the library
```
Why most truncated LTRs were filtered out and what's the criteria used for filtering?

Bests,

Karl

**Comment by oushujun** [comment]
Hi Karl,

You may minus solo and intact LTRs and the rest are truncated. If you have
a particular definition of truncated LTR, you need to set up your own
filters.

Most truncated LTRs have corresponding intact versions. Only the novel
truncated LTR sequences are retained in the library.

Shujun

**Comment by xiaoyezao** [comment]
From which file to minus solo and intact LTRs? Is it `.LTRlib.redundant.fa` ?

Thank you Shujun.

**Comment by oushujun** [comment]
Hello, it should be the whole genome annotation, so the gff3 file.

Shujun
